### ISSUE TITLE
Windows are completely black

### ISSUE THREAD

**Issue by guhur** [VirtualGL/virtualgl#103]
This is related to https://github.com/VirtualGL/virtualgl/issues/62.

I am trying to forward a GUI client from my remote machine using VirtualGL.

From my local machine, I connect to the remote machine with:
```
$ vgl_connect [hostname]
```

Here `xlogo` provides me the expected window. Confident, I launch:

```
vglrun +v  glxgears
[VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
[VGL]    128.93.65.54, the IP address of your SSH client.
[VGL] Shared memory segment ID for vglconfig: 4816899
[VGL] VirtualGL v2.6.2 64-bit (Build 20190522)
[VGL] Opening connection to 3D X server :0
[VGL] Using Pbuffers for rendering
```

and I can not get more than a black window.

It is worth to say that:
```
$ echo $DISPLAY
cooper:11.0
$ echo $VGL_DISPLAY

```

Also, my `.ssh/config` sets `XForwarding` and `XForwardingTrusted` to `yes`. Finally, `vglserver_config` displays:

```
... Creating /etc/modprobe.d/virtualgl.conf to set requested permissions for
    /dev/nvidia* ...
... Granting write permission to /dev/nvidia-modeset /dev/nvidia-uvm /dev/nvidia-uvm-tools /dev/nvidia0 /dev/nvidiactl for all users ...
... Modifying /etc/X11/xorg.conf to enable DRI permissions
    for all users ...
... Adding xhost +LOCAL: to /etc/gdm3/Init/Default script ...
... Creating /usr/share/gdm/greeter/autostart/virtualgl.desktop ...
... Disabling Wayland in /etc/gdm3/custom.conf ...

Done. You must restart the display manager for the changes to take effect.
```

**Comment by dcommander** [comment]
Try setting `X11UseLocalhost=yes` in **/etc/ssh/sshd_config** on the server, restarting the SSH server, and reconnecting using `vglconnect`.  The most immediate effect this should have is to change the value of the `DISPLAY` environment variable in the SSH session (it should now have the form of `localhost:{n}.0`.)

**Comment by dcommander** [comment]
Did that solve the problem?  Please do not close an issue without replying to it.

**Comment by guhur** [comment]
Yes that was my problem. It is solved now. Thanks!
