### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [VirtualGL/virtualgl#111]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [ClientWin](https://github.com/VirtualGL/virtualgl/blob/86343debafd3daf2fec025870f6b4bafc1ab86c6/client/ClientWin.cpp#L50 "Destructor for ClientWin")
- [VirtualWin](https://github.com/VirtualGL/virtualgl/blob/0d4c5ea5d34d84430abc6d661d392f6ce670aeed/server/VirtualWin.cpp#L86 "Destructor for VirtualWin")
- [VGLTransReceiver::listen](https://github.com/VirtualGL/virtualgl/blob/86343debafd3daf2fec025870f6b4bafc1ab86c6/client/VGLTransReceiver.cpp#L118 "VGLTransReceiver::listen function")

**Comment by dcommander** [comment]
Those are a product of VirtualGL's legacy.  In 2004, when some of those classes were first developed, not all compilers conformed to the C++ spec (Visual C++ 6.0, in particular, was problematic.)  I agree that they can be cleaned up-- particularly since VGL only supports GCC-compatible compilers these days.

**Comment by elfring** [comment]
How do you think about to improve affected source code places by using smart pointers?

**Comment by dcommander** [comment]
I have no interest in using smart pointers at this time.

**Comment by elfring** [comment]
Would you like to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by dcommander** [comment]
I will remove the unnecessary NULL pointer checks that were the root of this issue.  I do not intend to do anything else at this time.

**Comment by elfring** [comment]
How do you think about to apply a corresponding update suggestion which could be generated by [the software “Coccinelle”](http://coccinelle.lip6.fr/ "Source code transformation with Coccinelle")?

```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (\(x != 0 \| x != NULL\))
    free(x);
```

**Comment by dcommander** [comment]
Please stop asking me what I think about software I have never used.  If you know of a specific piece of software that detects these issues, then recommend it to me and provide instructions for its use.  I do not have time to go down rabbit holes on this.
