### ISSUE TITLE
Fix a mismatching allocation and deallocation for the variable “buf”

### ISSUE THREAD

**Issue by elfring** [VirtualGL/virtualgl#112]
[A source code analysis](https://wiki.sei.cmu.edu/confluence/display/cplusplus/MEM51-CPP.+Properly+deallocate+dynamically+allocated+resources#MEM51-CPP.Properlydeallocatedynamicallyallocatedresources-NoncompliantCodeExample%28new%29 "Properly deallocate dynamically allocated resources.") by the tool “cppcheck 1.88-24.d_t.13” points [a questionable implementation detail](https://github.com/VirtualGL/virtualgl/blob/2ebd888e9e844adf206215df617d139ec8a83b25/client/vglclient.cpp#L108 "Update candidate: killproc()") out.
The function “free” is called for the variable “buf” which got eventually a pointer by a new operator in the function “killproc”.

**Comment by dcommander** [comment]
Which cppcheck arguments did you use?  I attempted to reproduce the error but could not.

**Comment by elfring** [comment]
Which version did you try out for this analysis tool?

**Comment by dcommander** [comment]
1.88

**Comment by elfring** [comment]
Would you like to [change the implementation of the function “killproc” anyhow](https://github.com/VirtualGL/virtualgl/blob/2ebd888e9e844adf206215df617d139ec8a83b25/client/vglclient.cpp#L108 "Update candidate: killproc()")?

**Comment by dcommander** [comment]
Would you like to answer my question? How did you detect the issue using cppcheck? What arguments did you use? I need to reproduce your results so I can test for similar issues in an automated manner, so as to avoid them in the future.

**Comment by elfring** [comment]
>How did you detect the issue using cppcheck?

My development attention was increased in a software area for a moment by using supported plugins also for the application “KDevelop 5.4.5-75.1”.


>What arguments did you use?

I can reproduce the error report easily.

```
elfring@Sonne:~/Projekte/VirtualGL/lokal/client> cppcheck vglclient.cpp
…
Checking vglclient.cpp: __APPLE__...
[vglclient.cpp:122]: (error) Mismatching allocation and deallocation: buf
…
```


>I need to reproduce your results so I can test for similar issues in an automated manner, …

* How many efforts would you really like to invest in better source code analysis?
* Which information sources will you take into account finally?

**Comment by dcommander** [comment]
Still can't reproduce:

```
> cppcheck client/vglclient.cpp 
Checking client/vglclient.cpp ...
Checking client/vglclient.cpp: USESSL...
Checking client/vglclient.cpp: USEXV...
Checking client/vglclient.cpp: __APPLE__...
Checking client/vglclient.cpp: sun...
```

I will fix the specific issue, but please stop bugging me with more general questions.  I don't have time to nit-pick every aspect of this source code.  Every minute I spend on these activities is a minute I cannot spend adding new features or meaningfully improving the project.  Again, I am interested mainly in user-visible bugs, not in hypothetical bugs.  If a code purity issue is likely to cause a real-world problem, then I'm happy to fix it, but I don't have time to hunt for such issues.  The best way to ensure the purity of this source code is to come up with an automated workflow that reliably detects such issues.
