### ISSUE TITLE
Incorrect path for MacOS libGL.1.dylib

### ISSUE THREAD

**Issue by dgriffiths3** [VirtualGL/virtualgl#119]
I am trying to run version 2.6.3 with MacOS Catalina (10.15.4) as a client. The installation goes fine, however, when I try to run:

```
/opt/VirtualGL/bin/vglconnect <username>@<server_ip>
```

I get the error:

```
dyld: Library not loaded: /usr/X11/lib/libGL.1.dylib
  Referenced from: /opt/VirtualGL/bin/vglclient
  Reason: image not found
  [VGL] ERROR: vglclient failed to execute.
```

The file `libGL.1.dylib` is stored in `/opt/X11/lib` and **not** `/usr/X11/lib`. I have tried to make a symlink but MacOS already has a X11 link in `/usr` for something else and I can not change this.

**Comment by dgriffiths3** [comment]
Solved this. You can just symlink if you disable Catalina system file restrictions. Works once you add the symlink.

**Comment by dcommander** [comment]
Should be fixed now.  Refer to commit log for explanation.
