### ISSUE TITLE
Proprietary driver license

### ISSUE THREAD

**Issue by vtALEXANDER** [VirtualGL/virtualgl#128]
Good evening!

Thank you for your work and time. The question is about licensed use of proprietary AMD or NVIDIA drivers. The operating system of server and client — Linux.

Our goal is 8-15 remote workplaces for beginner students in Blender. As a solution we opened VirtualGL and, yes, it works! Your work provides a good technical solution! But the question is, will we violate the license of proprietary AMD or NVIDIA drivers by such use?

The following is not clear in licenses: 
NVIDIA - 2.1.3 Limitations. - Customer may not ... rent ... or use the SOFTWARE for public performance or broadcast. No Datacenter Deployment (??). 
AMD- 3. RESTRICTIONS - assign or otherwise transfer the Software. 

To what type the use of a proprietary driver belongs his use through VirtualGL? If students connect to a teacher's computer with an AMD or NVIDIA video card through VirtualGL and use Blender, will teacher/students violate terms of a proprietary driver license? Is it better to get an AMD video card? Are there other variants/solutions?

Thank you!

**Comment by muratmaga** [comment]
This is really a question to AMD and/or Nvidia not for virtualGL. I suspect if you are indeed an educational institution and not doing this profit, they probably wouldn't care. But you if you are concerned you need to seek clarification from the vendors, and probably with your legal team, not from a public forum.

**Comment by vtALEXANDER** [comment]
Thank you for your answer. 

Students pay for education. Small classroom. I assumed, that I have already encountered with this question here and though, that may be someone will give advice. 

As I understand, that AMD's video card’s open-source driver is in the better level than NVIDIA. Could it be easier to buy an AMD video card (rx580 or other) and use open-source drive + VirtualGL? 

Will this work? 

Thank you!

**Comment by muratmaga** [comment]
AMDs recent line up have all GL_MAX_3D_TEXTURE_SIZE < 2K, which is a non starter for our applications. So I have very little experience with AMD cards. I think (not sure) Quadro's do not have the 'no data center deployment' provisions (as they are supposed to be for professional work). So you might be fine using them. I -again think- those restrictions for Nvidia started after their 4XX series drivers, perhaps you might just use an older version that doesn't have those restrictions.

**Comment by dcommander** [comment]
@muratmaga On legal matters such as these, please allow me to answer first in an official capacity.  Thanks.

@vtALEXANDER 

- Unfortunately, there are [fundamental GLX conformance issues](https://groups.google.com/d/msg/virtualgl-users/vRcV9NTBgQM/-fJDwZWUAwAJ) in the "AMDGPU" and "AMDGPU Pro" drivers that need to be addressed before I can recommend them.  I have a modern AMD GPU in my lab, so once those issues are rectified, I will be able to test and certify the AMDGPU drivers with VirtualGL.  In general, however, there are other issues with the drivers-- including lack of GLVND support and lack of support for device-based EGL access-- that fail to impress me.  The VirtualGL Project is vendor-neutral, but I can only recommend what works, and right now, NVIDIA's drivers work best.  AMD has been informed of the issues with their drivers.
- There are large companies that deploy 3D applications using VirtualGL and server-side NVIDIA drivers to hundreds of users, so apparently none of the in-house attorneys for those large companies consider the NVIDIA license to be an issue.
- The driver license is under **/usr/share/doc/NVIDIA_GLX-1.0/LICENSE**.  On my machine, which is running v440.xx, the license does not mention anything about "public performance or broadcast."  Where are you seeing that clause?  As far as I can tell, it doesn't exist in the Linux drivers.
- Specific notes about the license:
    - 2.1.1: "Customer may install and use multiple copies of the SOFTWARE on a shared computer ... solely for Customer's use within Customer's Enterprise", and "Enterprise" is defined to include universities, which are paid educational institutions.
    - 2.1.2 provides an exception for Linux and FreeBSD that allows the drivers to be copied and redistributed.

I don't see anything in the license that would preclude its use in a shared remote environment.  If there were such limitations, then they would affect all remote software that uses the GPU.  That doesn't just include VirtualGL.

**Comment by vtALEXANDER** [comment]
Thank you for your answer! You made my day calmer. Thank you.

I will focus on NVIDIA cards before solutions with AMD.

I read the license agreement on the official NVIDIA website, compared in Linux. You're right! There are no point "public performance or broadcast." in Linux.

On point 2.1.1: we are a private small company, we do not classify as a university. It alarmed. 
On point 2.1.2: due to a lack of specific technical knowledge I didn’t know could the actually possible use of the proprietary NVIDIA driver together with a student thought VirtualGL be considered as "may be copied and redistributed". 
On point 2.1.3: No Rental. We rent, but our students accordingly temporarily use the driver, using Blender. I hope, that exceptions for Linux are more important =).

I asked a similar question at NVIDIA support. There is no answer yet. If it will be, I can duplicate it here.

**Comment by dcommander** [comment]
2.1.1: The license defines "Enterprise" as "individual use by Customer or any legal entity."  Private small companies are legal entities.

2.1.2: VirtualGL doesn't copy or distribute the GPU drivers.  It simply uses them.  Legally, it would be no different if you:
- Left the GPU-connected X server (which we call the "3D X server") logged in and ran `xhost +LOCAL:` on it
- Users connected to the server machine via SSH and ran `glxinfo --display :0`

That procedure involves the nVidia GPU drivers in exactly the same way that VirtualGL involves those drivers.  The only difference between that use case and a physically shared machine, i.e. a machine that allows multiple users to log in locally and use the GPU, is that VGL allows multiple users to use the GPU simultaneously.  However, simultaneous use of the GPU by multiple users is not forbidden by the nVidia license.

All of that aside, 2.1.2 basically says that 2.1.1 doesn't apply for the Linux and FreeBSD drivers ("notwithstanding" = "in spite of".)  So even if VGL were copying or distributing the GPU drivers, it would still be OK as long as VGL copied or distributed the Linux or FreeBSD drivers.  Some Linux distributions-- Ubuntu, for instance-- take advantage of that provision and provide their own binary packages for the nVidia proprietary drivers.

2.1.3: Software rental is a clearly-defined legal concept in the U.S., via the [Computer Software Rental Amendments Act of 1990](https://en.wikisource.org/wiki/Computer_Software_Rental_Amendments_Act_of_1990).  That law specifically excludes "a computer program which is embodied in a machine or product and which cannot be copied during the ordinary operation or use of the machine or product" from the definition of software rental.  In other words, under U.S. law, renting access to a shared machine on which a piece of software is installed does not qualify as renting said software, but if you aren't directly charging for access to the machine, it's a non-issue anyhow.

DIsclaimer: I am not a lawyer.  My opinion is to the best of my knowledge, which is based on decades of experience dealing with (and in some cases even writing) software licenses and funded development contracts, but my opinion should not be construed as a legal opinion.

**Comment by vtALEXANDER** [comment]
Good evening! Your answers are truly user-frendly, help good, if they will be visible to others, they can help them.

The last “rock” from “N” - on point 2.1. - ...non-transferable right to use the SOFTWARE… students, who study with us, aren’t workers of our company, there is only contract on education. Can we consider it «individual use by Customer», and that we don’t «non-transferable right to use the SOFTWARE»?
In its turn, point 2.1.2. ostensibly mentions an exception for LINUX only for copy and redistribution. Or «Notwithstanding the foregoing terms» even so relate to all 2.1.1. point?

Did I understand correctly – paying attention to «Figure 3.1: The VGL Transport with a Client-Side 2D X Server», students, connecting to a teacher’s computer, don’t use GPU Driver directly, but receive the result from VirtualGL, which is set on “server” of our company, therefore, don’t violate «non-transferable right to use the SOFTWARE»? ( P.S. loudly about a simple computer with gtx1060).

Nvidia answered in theyre style – sent to ask this question on forum developer.nvidia.
Radeon wrote that question ir rederected.

Thank you.

**Comment by dcommander** [comment]
- In 2.1, "non-transferrable" refers to the right (license) to use the software, not to the software itself.  In other words, only nVidia grants you the right to use their software.  You cannot grant a third party the right to use nVidia's software or receive that right from a third party.  This is a standard provision in most proprietary software licenses.  "Transfer" of the right to use software is not the same as "distribution" or "copying" of the software itself.
- 1.1 defines "Customer" as either an individual or entity.  Your organization is an entity, and thus you are not "transferring" the right to use the software, nor are you "distributing" the software, if you are merely using it internally to your organization.
- I don't understand your question about 2.1.2.  As I indicated, that provision seems to negate 2.1.1 if you are using a FreeBSD or Linux system, but again, that refers to copying and distribution of the software, which VirtualGL does not do.

Again, I'm not a lawyer, and my opinion should not be construed to be a legal opinion.  But numerous large corporations are deploying VirtualGL for internal use, and their in-house counsels have apparently not found the nVidia driver license to be problematic.

**Comment by vtALEXANDER** [comment]
Good afternoon.

Thank you for your help, now we can develop education of 3D modeling with new strenght and opportunities.

Additionally, in the NVIDIA forum we have received positive answer to this question, perhaps, besides us this could be useful to someone else (link below).

https://forums.developer.nvidia.com/t/question-about-license-for-customer-use-of-nvidia-software-for-linux/145910 

Thank you.
