### ISSUE TITLE
ERROR: OpenGL error 0x0502

### ISSUE THREAD

**Issue by ihauh** [VirtualGL/virtualgl#129]
Hello, I'm on Ubuntu 20.04, nvidia driver 440. Virtualgl not working, e.g.:

```
vglrun +v glxgears
[VGL] Shared memory segment ID for vglconfig: 32802
[VGL] VirtualGL v2.6.4 64-bit (Build 20200626)
[VGL] Opening connection to 3D X server :0
[VGL] Using Pbuffers for rendering
[VGL] Using pixel buffer objects for readback (BGR --> BGRA)
[VGL] ERROR: OpenGL error 0x0502
[VGL] ERROR: in readPixels--
[VGL]    463: Could not Read Pixels
```
This error started on Ubuntu 18.04 actually. I used to be able to connect to this machine via command line and vglconnect.

Thanks for any help!

**Comment by dcommander** [comment]
Are you using nVidia's distribution of the driver or Ubuntu's distribution of the driver?

**Comment by ihauh** [comment]
Ubuntu's, via `apt install nvidia-driver-440`

**Comment by dcommander** [comment]
Try uninstalling Ubuntu's distribution and installing nVidia's distribution.  That's the only suggestion I have.  I am actively using 440.xx on a CentOS 7 machine with no issues.

**Comment by dcommander** [comment]
What specific GPU model are you using?

**Comment by ihauh** [comment]
The machine has two Nvidia RTX 2070 cards.

**Comment by dcommander** [comment]
OK, if installing nVidia's distribution doesn't work, try running `/opt/VirtualGL/bin/glreadtest` and `/opt/VirtualGL/bin/glreadtest -alpha` on the local display.  If you get a similar error with `/opt/VirtualGL/bin/glreadtest` but not with `/opt/VirtualGL/bin/glreadtest -alpha`, then you may be able to make VirtualGL work properly by setting `VGL_FORCEALPHA=1` in the environment.

**Comment by ihauh** [comment]
These two commands give no errors with the repo driver. I'll try nVidia's run file -- however in the past I never had much luck with those.

**Comment by ihauh** [comment]
Maybe some progress: I just noticed vglrun works by setting VGL_DISPLAY=:1.0 or VGL_DISPLAY=:1.1

**Comment by ihauh** [comment]
Correction, it works locally but via vglconnect setting display=:1.0 (the only one it connects to), glxgears opens a window but it's just black and I have to CTRL+C to close it.

**Comment by dcommander** [comment]
> Maybe some progress: I just noticed vglrun works by setting VGL_DISPLAY=:1.0 or VGL_DISPLAY=:1.1

`VGL_DISPLAY` should point to the X server that has a GPU attached.  At this point, I need to ask more specifics about your server configuration.  Which X servers are running on which displays?  Which have GPUs attached?  Which GPUs?

**Comment by ihauh** [comment]
No luck with nVidia's own driver ver. 450, which is installed now.
X is running on GPU 0, which has the monitor attached. GPU 1 is basically idle.

**Comment by dcommander** [comment]
Your system apparently has X servers on both Display :0 and :1. Which is which?

**Comment by dcommander** [comment]
NOTE: I assert that because, in your original post, the VGL log shows it successfully connecting to :0.0, then when you changed `VGL_DISPLAY` to :1.0, you were able to use VGL successfully as well. So which display has the GPU?

**Comment by ihauh** [comment]
I'm not sure what's going on to be honest, glxgears works (locally) if I set display 1.0:
```
VGL_DISPLAY=:1.0 vglrun glxgears
7867 frames in 5.0 seconds = 1573.270 FPS
```
On 0.0 (default) it gives error 0x0502; it can't connect to displays 0.1 and 1.1. 

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 207...  Off  | 00000000:0A:00.0  On |                  N/A |
|  0%   31C    P8     9W / 215W |    378MiB /  7979MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 207...  Off  | 00000000:0B:00.0 Off |                  N/A |
|  0%   29C    P8    17W / 215W |      4MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1638      G   /usr/lib/xorg/Xorg                 35MiB |
|    0   N/A  N/A      3265      G   /usr/lib/xorg/Xorg                119MiB |
|    0   N/A  N/A      3479      G   /usr/bin/gnome-shell              100MiB |
|    0   N/A  N/A      3880      G   ...AAAAAAAAA= --shared-files      107MiB |
+-----------------------------------------------------------------------------+
```

**Comment by ihauh** [comment]
> NVIDIA gives GL_INVALID_OPERATION (0x502) if you've switched away from the graphical console. https://stackoverflow.com/a/22546103/176800 Are you doing that?

No I'm in Ubuntu's default Gnome.

**Comment by dcommander** [comment]
@ihauh When you ran `vglserver_config`, did you answer "yes" to the question about Wayland?  If you didn't, then that could be an explanation for why there are two X servers running.  If you didn't re-run `vglserver_config` after upgrading to Ubuntu 18.04 or after upgrading from VGL < 2.6.2 to VGL >= 2.6.2, then that could explain the issues.

**Comment by ihauh** [comment]
I reran the script answering yes to the Wayland question, no change.

**Comment by dcommander** [comment]
Did you reboot the machine after re-running the script?

**Comment by ihauh** [comment]
Yes; now when I try `vglconnect` + `vglrun glxgears` remotely I get no errors and a black window.

**Comment by ihauh** [comment]
@dcommander Can you maybe tell me what options I should select in `vglserver_config`, if you think that's going to help? I need to be able to use Ubuntu desktop in that machine as well as virtualgl remotely.

**Comment by dcommander** [comment]
The Wayland question was the only one that was likely to be relevant to this bug.  At this point, I would suggest trying an X proxy, such as TurboVNC.  Since you are not getting errors with `vglconnect` + `vglrun glxgears`, that means that the original problem is solved.  A blank window with `vglconnect` can sometimes happen due to a VGL Transport issue, which is unrelated to your original issue.

NOTE: At the moment, VGL has to turn off Wayland on the server in order to avoid issues such as the one you reported here.  Thus, you will be able to log in locally on the server, but you won't be able to run Wayland applications.

**Comment by dcommander** [comment]
Also, please endeavor to be precise in your descriptions.  You said "no change", but that wasn't correct.  The fact that the OpenGL error no longer occurs is a very significant change.

**Comment by ihauh** [comment]
Ok thanks, should I open a new issue about VGL Transport? I don't want to waste your time.

**Comment by dcommander** [comment]
No. Check the VGL client log under **~/.vgl/** on the client machine and verify that the server is connecting and that there aren’t any errors. If there aren’t, then I have no clue why the VGL Transport isn’t working for you. Maybe Port 4242 isn’t open in your client machine’s firewall? Have you tried `vglconnect -s`?

**Comment by ihauh** [comment]
Log files are empty. Tried `vglconnect -s` and it actually works--however at one fps. This is weird as I'm sure I tried it yesterday and I still got a blank window.

**Comment by dcommander** [comment]
Let's back up for a moment.  There are three separate issues at work, here.

1. The OpenGL error you initially reported was very likely due to the fact that modern GDM releases use Wayland by default, which means that VirtualGL can't connect to the 3D X server while the 3D X server is sitting at the login prompt. (With GDM/Wayland, the 3D X server either isn't running at the login prompt, or it is running on top of Wayland and thus can't be assigned the proper permissions for use with VirtualGL.)  VGL 2.6.2 introduced changes to `vglserver_config` that work around this problem by forcing GDM to use X11 rather than Wayland.  Unfortunately, that disables local Wayland logins, but:

    1. Most systems that are configured for use as VirtualGL servers aren't used for local logins.

    2. Best practices are to not allow local logins on the 3D X server, because when someone logs in and out locally, that will reset the 3D X server, thus causing any applications currently running with VirtualGL to abort.  If local logins are desired on a VGL server, best practices are to use a dedicated low-end GPU for the local console and a dedicated high-end GPU, configured for headless operation, for VGL.  If you're the only user of the machine, then it's fine to allow local logins on the 3D X server, but doing so requires either disabling local Wayland logins (by running `vglserver_config`) or logging in with an Xorg session and leaving the session logged in.

    Ubuntu 18.04 was the first Wayland-enabled Ubuntu release, which explains why VGL stopped working when you upgraded to that release.  VGL 2.6.2 was the first release that addressed that issue, and it was necessary to re-run `vglserver_config` after upgrading to VGL >= 2.6.2 in order to receive the fix.  Thus, when you re-ran `vglserver_config`, this issue was eliminated.

2. Given that you aren't seeing a connection message in the `vglclient` logs, it's very likely that the issue with `vglconnect` is due to a firewall on your client machine.  That explains why `vglconnect -s` works but `vglconnect` with no arguments doesn't.  As to why `vglconnect -s` didn't previously work, that was likely due to Issue 1 above.

3. The 1 fps performance issue is very likely due to #120, in which case modifying **xorg.conf** as recommended in that issue and restarting the 3D X server should resolve it.

**Comment by ihauh** [comment]
Thanks for the extensive explanation. Applying #120 the fps is decent.
The blank window problem seems to be more similar to #62 but I can't change my setup right now.

**Comment by dcommander** [comment]
Unlikely that it is the same issue as described in #62.  In that case, the poster was unable to use the VGL Transport at all.  You are able to use the VGL Transport with `vglconnect -s`.  That means that the server is working properly and that the issue is on the client.

**Comment by ihauh** [comment]
Sorry the firewall _on the client_ was in fact the problem. Pure `vglconnect` now works with good fps.
Solved! Thanks again

**Comment by Gansgar** [comment]
@dcommander I just wanna jump in and clarify one thing: Since Ubuntu 18.04 there are two Xorg servers running. One for the login page and one managing the user. Before that the login xorg was morphed into a user instance. See [this answer](https://askubuntu.com/a/1041403/1001909)

I'm using 18.04 and depending whether a user is logged in or not on the local machine, VGL run works or not.
I run my tests using FastX (which is similar to VNC) using User1 and testing with the 'glxspheres64` application

| Situation locally | VNC with `VGL_DISPLAY=:0` | VNC with `VGL_DISPLAY=:1` |
| --------------------- | ---------------------------------------- | ----------------------------------------|
| Login screen | works with every user | `Could not open display :1` |
| User1 logged in | 0x0502 crash | runs |
| User2 logged in | 0x0502 crash | `Could not open display :1` |

**Comment by dcommander** [comment]
@Gansgar Thanks for the clarification.  There unfortunately isn't anything we can do about that.  The configurations we can support are:
1. Leave the 3D X server at the login prompt and either:
    * Never log in locally (i.e. administer the system via SSH or VNC.)

   ...or...

    * Use a dedicated X server running on a different (perhaps lower-spec) GPU for local logins, and reserve the 3D X server solely for VirtualGL.
2. Use the new EGL back end (currently available for testing in the [3.0 evolving pre-release build](https://virtualgl.org/DeveloperInfo/PreReleases)), which eliminates the need for 3D X server access and thus eliminates any conflict between VirtualGL and local logins.

The only reasons I can fathom why anyone would want to log in locally on a VGL server are:
- The machine is their personal workstation.  (But if that's the case, why would they also need to allow other users to access it remotely?)
- The machine is a server, and they want to administer it.  (But that can be done in other ways.)

Even on older O/S distributions that re-used the same X server connection between the display manager and the local login, the display manager would still reset the X server connection when the user logged out, and that had the effect of killing any applications that were currently running in VGL.  The last time I can remember when logging in locally didn't adversely affect VirtualGL was about 15 years ago.  It just isn't a supportable configuration these days, unless the VirtualGL server truly is a single-user machine.

In the long term, the EGL back end will make these sorts of issues moot, but at the moment, the EGL back end only works properly on nVidia hardware and drivers.

**Comment by karlkleinpaste** [comment]
Just FYI regarding...

> The only reasons I can fathom why anyone would want to log in locally on a VGL server are:
> The machine is their personal workstation. (But if that's the case, why would they also need to allow other users to access it remotely?)

I can offer one concrete reason: I need to allow myself alternate access.

Personal machine, MATE + compiz. My company produces simulation software that's written for Win32 API but exists in the Linux space via a compatibility layer called Mainwin, providing a Win32-acceptable view of Linux processes, filesystem, signals, and window system. A bad side effect is that Mainwin programs do not get along with compiz, for reasons I've never been able to grok.

My solution (workaround) is blunt: I keep a couple TurboVNC sessions active on the same machine, where I use VGL for working with our software, typically 1 with GNOME and 1 that's maximally stupid with nothing but mwm + terminal. (I truly dislike GNOME but of course our software is Officially Supported under it, so...)

Perhaps some day I'll figure out what compiz has against Mainwin apps or vice versa, but I've looked a couple times, to no benefit so far.

**Comment by dcommander** [comment]
Yes, and I allowed for that use case in my comment above.  I just don't understand why that use case would need to allow users other than you to access the machine.  If it's a single-user machine, i.e. if only you can access it, then it's straightforward for you to manage access to the 3D X server whether or not it is logged in.  If it's a multi-user machine, it's impossible to manage that access in a secure manner.
