### ISSUE TITLE
Origin signature check fails against SourceForge download

### ISSUE THREAD

**Issue by lynnpepin** [VirtualGL/virtualgl#131]
Hi,

I've downloaded the `virtualgl_2.6.4_amd64.deb` from the SourceForge repository linked to [here](https://sourceforge.net/projects/virtualgl/files/).

I attempt to verify using the instructions in [https://virtualgl.org/Downloads/DigitalSignatures](https://virtualgl.org/Downloads/DigitalSignatures), but I get the following output:

```debsig: Origin Signature check failed. This deb might not be signed.```

Is anyone else having this issue? Is anyone able to get their .deb files to sign correctly?

**Comment by dcommander** [comment]
Confirmed and investigating.  This seems to have been introduced when I upgraded the Docker container prior to VirtualGL 2.6.3.

**Comment by dcommander** [comment]
New DEB packages with proper signatures are now available for VGL 2.6.3 and 2.6.4 on SourceForge.

If you are using a newer release of Ubuntu or Debian, then re-download the **debsig-import** script from https://virtualgl.org/Downloads/DigitalSignatures.  If you have already imported the key using an old version of **debsig-import**, then do:

```
sudo debsig-import -d 6BBEFA1972FEB9CE
```
before proceeding with the verification instructions.
