### ISSUE TITLE
question: vgl inside virtualbox: gui start

### ISSUE THREAD

**Issue by karlkleinpaste** [VirtualGL/virtualgl#132]
Scenario:
Centos 7 physical machine, nvidia Quadro M4000.
Regular console X server (":0"), no one logged in, available to anyone (which means me, it's my box).
Faker libs were made setuid-root.
TurboVNC Xvnc, started via vncserver with -vgl.
The desktop within was started as "vglrun mate-session". (I don't use the provided xstart.turbovnc, but rather a custom xstart.)
WM started as "vglrun +wm compiz". (Not sure I needed +wm there, but I'm OK with being redundant.)
Latest VBox.
VM _**started from the GUI**_.

Question:
The guide @ file:///usr/share/doc/VirtualGL-2.6.4/index.html#hd0013 says:

> "It is necessary to start the virtual machine directly as described above. Simply executing vglrun VirtualBox and using the GUI to launch the VM does not work. VirtualBox forks a separate process for each VM, and the value of the LD_PRELOAD environment variable from vglrun does not get propagated to the VM process unless you start it directly."

This seems to be not correct, or perhaps no longer correct.
I have a one-line shell script, list-libs, that dumps linked libs
`cat /proc/"$1"/maps | awk '{ print $6 }' | sort | uniq
`
I see this:
```
# ps aux | grep -i virtualbox
kkleinpa 30163  0.4  0.2 1629288 193004 ?      Sl   Aug14   6:42 /usr/lib/virtualbox/VirtualBox
kkleinpa 12757 22.7  6.5 29357628 4333224 ?    Sl   Aug14 329:26 /usr/lib/virtualbox/VirtualBoxVM --comment EBU-Dev-VM-C8 --startvm 281407c1-f955-4268-b840-7300050efb9b --no-startvm-errormsgbox
kkleinpa 30207  0.7  0.0 1330640 24260 ?       Sl   Aug14  10:56 /usr/lib/virtualbox/VBoxSVC --auto-shutdown
kkleinpa 30198  0.2  0.0 236004  7604 ?        S    Aug14   3:46 /usr/lib/virtualbox/VBoxXPCOMIPCD
# list-libs 12757 | egrep -i fake\|libgl\|nvidia
/dev/nvidia0
/dev/nvidiactl
/usr/lib64/libdlfaker.so
/usr/lib64/libglapi.so.0.0.0
/usr/lib64/libGLdispatch.so.0.0.0
/usr/lib64/libglib-2.0.so.0.5600.1
/usr/lib64/libGL.so.1.7.0
/usr/lib64/libGLX_mesa.so.0.0.0
/usr/lib64/libGLX_nvidia.so.440.100
/usr/lib64/libGLX.so.0.0.0
/usr/lib64/libnvidia-glcore.so.440.100
/usr/lib64/libnvidia-tls.so.440.100
/usr/lib64/libvglfaker.so
```
Note that the VM process has the faker libs linked, plus the nvidia-specfic libs, and has control of the devices as well.
Also, nvidia-smi on the host observes the VM's presence:
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     12757      G   /usr/lib/virtualbox/VirtualBoxVM             109MiB |
```
It seems to me that LD_PRELOAD propagated fine and the entirety of VGL machinery is in play.  Am I missing something?

**Comment by karlkleinpaste** [comment]
The background reason I'm asking is that I'm getting no effect of invoking with VGL, by GUI or by command line invocation.
The VM is Centos 8. It seems to have precisely the same behavior between being started with vglrun and without it.  I get respectable behavior of glxgears and glxspheres64, but no difference (certainly no improvement) with VGL attempted. In either situation, with or without VGL, there is this, where the renderer string is typical for 3D-accelerated VM graphics:
```
$ glxinfo64 | grep -v '^[0 ]'
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
GLX version: 1.4
GLX extensions:
Extended renderer info (GLX_MESA_query_renderer):
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: SVGA3D; build: RELEASE;  LLVM;
OpenGL version string: 2.1 Mesa 20.1.2
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 20.1.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
SVGA3D is the usual "3D Acceleration enabled" string; I would have expected to see an nvidia-oriented string there.
```
The VBoxVM process has relevant env.vars set, but I get neither profiling on the terminal where I start it, nor the bottom-right logo.
```
# ps aux | grep -i virtualboxvm
kkleinpa 17400 65.3  6.2 7758812 4111076 pts/11 Sl  13:14   7:51 /usr/lib/virtualbox/VirtualBoxVM -startvm EBU-Dev-VM-C8
# cat /proc/17400/environ|nuls|sort|egrep ^'(VGL|TVNC|LD)'
LD_PRELOAD=libdlfaker.so:libvglfaker.so
TVNC_VGL=1
VGL_COMPRESS=0
VGL_ISACTIVE=1
VGL_LOGO=1
VGL_PROFILE=1
VGL_VERBOSE=1
```
Any thoughts are welcome.

**Comment by dcommander** [comment]
I'll look into it.  Perhaps something changed in more recent VirtualBox releases.

**Comment by dcommander** [comment]
I just re-tested with VirtualBox 6.1.12 (latest version available as of this writing.)  I can confirm that it is no longer necessary to launch VirtualBox from the command line in order to use it with VGL.  Apparently the move from Chromium to SVGA3D in VirtualBox 6.1.0 eliminated the need to do that.  What's weird, however, is that 3D acceleration still requires VGL-- I get a software renderer in the guest if I don't use VGL-- but when running a 3D application in the guest, the VirtualGL trace log doesn't show anything, and `VGL_LOGO` doesn't work.  I do see a few GLX commands coming through from the VirtualBox process, mainly related to establishing a GLXFBConfig and obtaining a visual from it, which is used to create the VirtualBox window.  I don't see anything after that, though.  Notably, I don't see any calls to `glXCreate*Context*()` or `glXSwapBuffers()`.

**Comment by dcommander** [comment]
The VGL User's Guide has been updated with the current VirtualBox and VMware realities.  VirtualBox somehow bypasses VirtualGL's readback mechanism and image pipeline entirely, so nothing beyond the GLX interposer works.  In other words, VirtualGL will enable GPU acceleration, but no VGL features that are part of the readback mechanism or image pipeline will work.  No profiling, no `VGL_LOGO`, no PBO readback, no VGL Transport, no image transport plugins, etc.  In Windows guests, the OpenGL renderer string will change from "GDI Generic" to "SVGA3D" if 3D acceleration is working.  In Un*x guests, the only way to tell is to start the VM from the command line with VirtualGL tracing enabled (`vglrun +tr VirtualBoxVM -startvm {virtual-machine}`) and run a 3D application in the guest.  You should see various GLX commands in the trace log if VirtualGL is working, and performance should be visibly faster.

I don't have time to pore over the VBox code and figure out why it's bypassing most of VGL, but if someone in the community has time to do that, it would be nice to know if there's a way to work around that.  Just having the ability to use `VGL_LOGO` would make things a lot easier.
