### ISSUE TITLE
LD_LIBRARY_PATH issue with vglconnect

### ISSUE THREAD

**Issue by halowine** [VirtualGL/virtualgl#133]
Hello,

I’m trying to launch an application through vglconnect but my app fails to open. I think the problem comes from the LD_LIBRARY_PATH. 
My application need shared library path that I set in LD_LIBRARY_PATH. If I activate the verbose in vglconnect, I see that it’s resetting the LD_LIBRARY_PATH variable at startup :

NOTICE: Added /usr/lib64 to LD_LIBRARY_PATH

The problem is that my application crashes because it looks for the library in /usr/lib64 first before my /shared_path. The library is the libz.so and my system have old libz.so which lead to the crash. The correct libz.so version is in /shared_path. 

Is there a way to avoid the resetting of LD_LIBRARY_PATH at startup? Or to control the LD_LIBRARY_PATH afterward ?

In order to work, my LD_LIBRARY_PATH should be:
LD_LIBRARY_PATH=/shared_lib:/usr/lib64
By vglconnect forces:
LD_LIBRARY_PATH=/usr/lib64:/shared_lib:/usr/lib64

Thank you

**Comment by dcommander** [comment]
Huh?  `vglconnect` does not do anything to `LD_LIBRARY_PATH`.  That message comes from `vglrun` on the server, and it would only occur if you specified the `-ld` argument to `vglrun` or if you have a **.vglrun.vars64** file in the same path as `vglrun`.  Solution: don't specify `-ld`, or delete **.vglrun.vars64**.  (Note that our official packages do not include **.vglrun.vars64**.)
