### ISSUE TITLE
Basic usage of virtualgl

### ISSUE THREAD

**Issue by lepalom** [VirtualGL/virtualgl#141]
Probably I don't understand the usage of the virtualgl and I get some obvious errors. My setup is like this:

- A powerful server without with a simple graphics card.
- A remote computer with a powerful graphics card (Nvidia).

I would like to run a graphical application in the server and visualize it in the remote computer. I have installed virtualgl and configured.

If I connect to the server, using ssh -X. I can execute:

$ /opt/VirtualGL/bin/glxinfo -display :0 -c
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_fbconfig_float, GLX_ARB_framebuffer_sRGB, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_libglvnd, GLX_EXT_no_config_context, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_MESA_copy_sub_buffer, GLX_OML_swap_method, GLX_SGIS_multisample, 
    GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, GLX_SGIX_visual_select_group,

.....

but if I run:

$ vglrun glxgears
[VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
[VGL]    XX.XX.XX.XX, the IP address of your SSH client.
failed to create drawable
[VGL] ERROR: in OGLDrawable--
[VGL]    83: Could not create Pbuffer

Some idea please?

**Comment by dcommander** [comment]
Yeah, the problem is that you really need the powerful graphics card to be in the powerful server.  Apparently the simple graphics card doesn't support the GLX functionality that VirtualGL needs.  VirtualGL has two purposes-- GPU sharing (allowing multiple users of a remote machine to use the same GPU simultaneously) and server-side rendering (redirecting OpenGL rendering into off-screen buffers on a GPU in the server and then sending only the rendered images to the client, usually by way of a high-speed X proxy such as TurboVNC that couldn't support GPU acceleration without VirtualGL.)

**Comment by lepalom** [comment]
@dcommander thanks for the answer. But, following your answer, I have installed an Nvidia GeForce GT 620 (not a great card, but enough to make a test) and run again the commands. And I obtain the same result ... 

Should I have to activate something in the client? Or what do I miss?

**Comment by dcommander** [comment]
Did you install nVidia’s drivers?

**Comment by lepalom** [comment]
Well, in both boxes the nvidia drivers are installed. Both boxes run Debian Buster 10.

In the client:
- nvidia-driver  440.100-1~bpo10+1

In the server:
- nvidia-driver legacy 390xx, 390.138-1~deb10u1

**Comment by dcommander** [comment]
Double check that the output of `/opt/VirtualGL/bin/glxinfo -c` shows nVidia as the OpenGL renderer. If it doesn’t, then the 3D X server is misconfigured. If it does, then try setting `VGL_FORCEALPHA=1`.

**Comment by lepalom** [comment]
I'm a bit lost. After configure Xserver and some trouble with the permissions I got:
$ /opt/VirtualGL/bin/glxinfo -display :0.0 -c | grep ender
direct rendering: Yes
OpenGL renderer string: GeForce GT 620/PCIe/SSE2
.....

but if I run any application with vglrun or directly, the app load but nothing is showed in my remote desktop. Also, i have exported the VGL_FORCEALPHA=1 var.

What I'm doing wrong?

**Comment by lepalom** [comment]
Finally, I made it worked. 

The main problem is that modern GNU/Linux distros has IndirectGLX disabled by default. In my case, in a Debian Buster just adding this:

Section "ServerFlags"
    Option "IndirectGLX" "on"
EndSection

to /etc/X11/xorg.conf on the client, made it worked. Maybe could be a good idea to put it in some place of the documentation. At least it was a necessary step with an Nvidia proprietary driver.

**Comment by dcommander** [comment]
Uh, no.  In fact, VirtualGL's entire reason for being is to avoid indirect GLX.  If indirect GLX is required, then something is wrong.
