### ISSUE TITLE
VNC and ssh to remote host leads to X Error BadRequest invalid request code

### ISSUE THREAD

**Issue by paulraines68** [VirtualGL/virtualgl#142]
We are running VirtualGL 2.4.4 on CentOS 7.7 which has NVIDIA card and NVIDIA driver 418.87

Normally we are using NoMachine as a remote X GUI and vlgrun works fine there.  But on tigervnc server 1.8.0 on the Linux box and TurboVNC viewer on Windows, we are having problems.  vglrun is fine on simple apps like xeyes, but on complex apps like glxgears or glxspheres64 it fails with this error.  Actually it is fine on the same machine running the VNC server itself.  It only gives the following error when you have done 'ssh -Y' to another host (identical CentOS 7.7/VGL 2.4.4/NV 418.87)

tiamat[0]:~$ /usr/bin/vglrun -c proxy glxspheres64
[VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
[VGL]    172.21.16.104, the IP address of your SSH client.
[VGL] NOTICE: Added /usr/lib64/VirtualGL to LD_LIBRARY_PATH
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
[VGL] Shared memory segment ID for vglconfig: 1761280038
[VGL] VirtualGL v2.4 64-bit (Build 20150505)
[VGL] Opening connection to 3D X server :0
[VGL] NOTICE: Replacing dlopen("/lib64/libdl.so.2") with dlopen("libdlfaker.so")
Visual ID of window: 0x288
Context is Direct
[VGL] Using Pbuffers for rendering
OpenGL Renderer: Quadro K6000/PCIe/SSE2
X Error of failed request:  BadRequest (invalid request code or no such operation)
  Major opcode of failed request:  131 (MIT-SHM)
  Minor opcode of failed request:  1 (X_ShmAttach)
  Serial number of failed request:  13
  Current serial number in output stream:  14
tiamat[0]:~$ xdpyinfo | grep MIT
    MIT-SCREEN-SAVER
    MIT-SHM
tiamat[0]:~$ DISPLAY=:0
tiamat[0]:~$ export XAUTHORITY=/etc/opt/VirtualGL/vgl_xauth_key
tiamat[0]:~$ xdpyinfo | grep MIT
    MIT-SCREEN-SAVER
    MIT-SHM

Any ideas?

**Comment by dcommander** [comment]
So you are using `ssh -Y` within the TigerVNC session to connect to another host and run an application on that other host? If so, you need to use `vglconnect`. Refer to the TurboVNC User’s Guide.

**Comment by paulraines68** [comment]
Okay, I ran 'vglconnect' instead of 'ssh -Y' but the exact same BadRequest result when running "vglrun -c proxy glxspheres64"

I should add "vglrun -c proxy glxinfo" does work.

**Comment by dcommander** [comment]
I guess you didn’t refer to the User’s Guide. Do `vglrun -c rgb`, not `-c proxy`

**Comment by paulraines68** [comment]
That means I have to be using vglclient which just doesn't work.  So we have always used proxy when ssh to another box that has VGL installed just like on the box running VNC itself.  It has worked for NXFree, X2Go, and NoMachine over the past years like this but we just recently decided to try TigerVNC

When trying with vglclient, both on the machine running the VNC server or on the machine ssh'ed to from there (since both have VGL installed), we get the same result when trying to run any GLX based program like glxgears of glxspheres64

```
$ XAUTHORITY=/etc/opt/VirtualGL/vgl_xauth_key vglclient -force -display :0

VirtualGL Client 64-bit v2.5.2 (Build 20180529)
Listening for unencrypted connections on port 4242
++ Connection from 172.21.21.96.
X11 Error: BadWindow BadWindow (invalid Window parameter)
FBX-- 263: X11 Error (window may have disappeared)
-- Disconnecting 172.21.21.96
```

And on the vglrun side you get

```
[VGL] ERROR: Could not send data to client.  Client may have disconnected.
[VGL] ERROR: in send--
[VGL]    416: Broken pipe
```

If I leave off the -display it will connect to my VNC X11 server instead of the NVIDIA 3D X11 server and then it works for glxgears but at 1 frame per second

**Comment by dcommander** [comment]
`vglconnect` launches `vglclient`. Why are you launching `vglclient` manually? And setting `XAUTHORITY` to that value is incorrect and represents a misunderstanding of how VGL works.

**Comment by paulraines68** [comment]
Yes, sorry.  I did start out doing it the correct way but it did not work in a way that was usable.  It was slower
than not using VGL at all which is about 100 FPS

```
vncserverbox[0]:~$ vglconnect remoteclient1

VirtualGL Client 64-bit v2.5.2 (Build 20180529)
Listening for unencrypted connections on port 4242
Redirecting output to /homes/11/raines/.vgl/vglconnect-vncserverbox-:2.log

Last login: Mon Sep 21 13:03:14 2020 from vncserverbox
Kickstarted on 2018-08-07
remoteclient1[0]:~$ vglrun -c rgb glxgears
[VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
[VGL]    172.21.16.104, the IP address of your SSH client.
7 frames in 5.1 seconds =  1.371 FPS
5 frames in 5.0 seconds =  1.000 FPS
6 frames in 6.0 seconds =  1.000 FPS
5 frames in 5.0 seconds =  0.999 FPS
6 frames in 6.0 seconds =  1.001 FPS
^C

```
I erroneously thought this was because vglclient was somehow using the VNC server itself as the "3D" server. I started experimenting with different things like the XAUTHORITY and -display to just try different things.   My apologies for the red herrings from my ignorance. 

The above two boxes are running VirtualGL 2.5.2 and the same on other clients I have tried so far.  I found a client that still has 2.4 installed on it and decided for the hell of it to try it.  Lo and behond it works fine with the vglconnect method

```
vncserverbox[0]:~$ vglconnect oldremoteclient

VirtualGL Client 64-bit v2.5.2 (Build 20180529)
vglclient is already running on this X display and accepting unencrypted
   connections on port 4242.

Last login: Mon Sep 21 13:00:32 2020 from vncserverbox
Kickstarted on 2017-02-27
oldremoteclient[0]:~$ vglrun -c rgb glxgears
[VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
[VGL]    172.21.16.104, the IP address of your SSH client.
14556 frames in 5.0 seconds = 2911.080 FPS
16655 frames in 5.0 seconds = 3330.827 FPS
16554 frames in 5.0 seconds = 3310.640 FPS
^C
```

I upgraded a remoteclient to 2.6.4 but still get the 1 FPS on it.  

I then downgraded it to 2.4 but still get the 1 FPS on it. 

I have over one hundred Linux workstations with NVIDIA I administer.  I started randomly going around them to test and have since found 2.5.2 machines where it works fine too and 2.4 machines where it does not.

I also downgrade VirtualGL on the vncserver box to 2.4 but it made no difference to which clients worked and which gave 1 FPS.

So I am very confused at this point as I cannot see any clear difference in the machines where it works versus where I get 1 FPS at this point.  There is a mix of VirtualGL versions and NVIDIA driver versions.  I tried a couple of CentOS8 boxes too.
It is very suspicious that it is pretty much EXACTLY 1 FPS too

**Comment by karlkleinpaste** [comment]
We have previously been told that the 1 FPS problem is due to a driver flaw re: DPMS. Use `xset -dpms` and you will regain normal FPS rates.

**Comment by paulraines68** [comment]
Thanks, that works

```
vncserverbox[0]:~$ vglconnect remoteclient1

VirtualGL Client 64-bit v2.4 (Build 20150505)
vglclient is already running on this X display and accepting unencrypted
   connections on port 4242.

Last login: Mon Sep 21 14:57:33 2020 from remoteclient1
Kickstarted on 2018-09-02
remoteclient1[0]:~$ vglrun -c rgb glxgears
[VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
[VGL]    172.21.16.104, the IP address of your SSH client.
7 frames in 5.0 seconds =  1.396 FPS
5 frames in 5.0 seconds =  1.000 FPS
^C
remoteclient1[0]:~$ DISPLAY=:0 XAUTHORITY=/etc/opt/VirtualGL/vgl_xauth_key xset -dpms
remoteclient1[0]:~$ vglrun -c rgb glxgears
[VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
[VGL]    172.21.16.104, the IP address of your SSH client.
15015 frames in 5.0 seconds = 3002.828 FPS
14335 frames in 5.0 seconds = 2866.933 FPS
^C
```

It is curious that NoMachine does not need vglconnect.  Even worked without VirtualGL installed on the NoMachine server which was headless.  But I will train VNC users to use vglconnect.

**Comment by dcommander** [comment]
Also please bear in mind that those FPS numbers are meaningless unless you have disabled frame spoiling. Refer to the Performance Measurement section in the VGL User’s Guide. If you run a very simple application like GLXgears or even, in some cases, GLXspheres with default settings, the geometry is so small that the applications might render at high frame rates when using indirect GLX (that is, when transmitting all of the OpenGL commands over the network), but that will certainly not be the case with more realistic geometry sizes.  Look at the `HardDPMS` option in the nVidia README for information on how to permanently fix the 1 FPS problem on a particular system. Also, if you prefer not to use `vglconnect` in the TurboVNC session, you may be able to work around the issue by setting `VGL_USEXSHM=0` on the application server. However, `vglconnect`/`vglrun -c rgb` is still preferred, because that will use 1/4 less network bandwidth than `-c proxy`. `-c proxy` is designed only for X proxies running on the same machine as the application.

**Comment by paulraines68** [comment]
Thanks, that is great information

**Comment by dcommander** [comment]
I am out of the office, but when I return, I will also try to reproduce the original issue. VirtualGL should properly handle using the X11 Transport over SSH, even though that is not the recommended use case.
