### ISSUE TITLE
vg-client missing on windows?

### ISSUE THREAD

**Issue by chwba** [VirtualGL/virtualgl#144]
im trying to set this up on windows server 2019 to run an application which requires opengl but all i can find after installing is this:
![image](https://user-images.githubusercontent.com/22568014/95698068-0cacf080-0c41-11eb-8017-1417ec233b84.png)

**Comment by dcommander** [comment]
The VirtualGL-Utils package for Windows is just what it says-- supporting utilities for VirtualGL but no client.  The VirtualGL Client for Windows is now distributed as an official Cygwin package and can be installed using Cygwin Setup.  Note that most people don't use the VGL Transport/VirtualGL Client these days.  They use VirtualGL with an X proxy such as TurboVNC or Xpra, in which case the VirtualGL Client is not needed (you would instead install the client for the X proxy.)
