### ISSUE TITLE
package architecture (aarch64) does not match system (arm64) Errors were encountered while processing: virtualgl_2.6.5_aarch64.deb

### ISSUE THREAD

**Issue by marzban2030** [VirtualGL/virtualgl#145]
After git cloning virtualgl project and several hours source code compiling and deb package building, i got below error while i run "sudo dpkg -i virtualgl_2.6.5_aarch64.deb":

dpkg: error processing archive virtualgl_2.6.5_aarch64.deb (--install):                              package architecture (aarch64) does not match system (arm64)
Errors were encountered while processing:          virtualgl_2.6.5_aarch64.deb

*Note: arm64 and aarch64 is same.

**Comment by dcommander** [comment]
You are apparently building an Arm version of VirtualGL and trying to install it on an x86-64 system.

**Comment by marzban2030** [comment]
> You are apparently building an Arm version of VirtualGL and trying to install it on an x86-64 system.

No! It is arm64 hardware.
The linux operating system at this hardware compiled the source codes and built the package for itself; But itself built-in package have above problem that i said.

**Comment by dcommander** [comment]
Then why does the error message say "amd64"? That is the same as x86-64.

**Comment by dcommander** [comment]
Either I misread your original comment or there was a typo that has since been corrected.  I thought the error message said "amd64" rather than "arm64."  The issue in the build/packaging system has been corrected.

**Comment by marzban2030** [comment]
![121614265_231959198439514_1961689223806263605_o](https://user-images.githubusercontent.com/73051714/96617613-b3b01d00-1310-11eb-91eb-6251e44f8ae0.jpg)

**Comment by dcommander** [comment]
As I said, the issue is fixed in the master branch.  Check out the newest code and try again.  Posting a screenshot of the same error, which obviously was not the result of building the master branch, is not helpful.
