### ISSUE TITLE
ERROR: in fconfig_getinstance--

### ISSUE THREAD

**Issue by Heasterian** [VirtualGL/virtualgl#148]
Hi!

I'm trying to run VirtualGL with VM as client and armhf Debian chroot as running on my phone server. VGL connect worked well, but I'm getting error when I'm trying to run anything.

Server and client have turbojpeg and VirtualGL form last tarballs.

[VGL] ERROR: in fconfig_getinstance--
[VGL]    96: Function not implemented

**Comment by dcommander** [comment]
No idea. The implementation of `shmget()` in the server O/S seems to be failing for some reason-- perhaps because it's a chroot environment. You might try undefining `FCONFIG_USESHM`, which would disable the use of the VGL configuration dialog but may allow VGL to work otherwise. Your configuration is not even remotely supported, so there's very little I can do to help you.

**Comment by sunarowicz** [comment]
@Heasterian : Did you succeed to solve this somehow? I'm in the same boat now with virtualgl-3.1.1 and Ubuntu in chroot on arm64 phone. I get the following when trying to run anything with vglrun:
```
[VGL] ERROR: in fconfig_getinstance--
[VGL]    99: Function not implemented
terminate called after throwing an instance of 'util::UnixError'
  what():  99: Function not implemented
```

Any help much appreciated.

**Comment by dcommander** [comment]
@sunarowicz Have you tried rebuilding VirtualGL with `FCONFIG_USESHM` undefined, as I suggested above?

**Comment by sunarowicz** [comment]
@dcommander : No I haven't. To be honest, I didn't understand that I have to build VirtualGL myself. I've been installing it from deb package.

Allright, I will build it then. I checked the buid documentation, but it is too general for a VirtualGL newbie like me.  So I asked Claude for help. It advised me the following build parameters (I guess -DFCONFIG_USESHM=OFF is what we need here):
```
cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DTJPEG_INCLUDE_DIR=/usr/include \
    -DTJPEG_LIBRARY=/usr/lib/aarch64-linux-gnu/libturbojpeg.so \
    -DVGL_USESSL=1 \
    -DCMAKE_INSTALL_PREFIX=/opt/VirtualGL \
    -DFCONFIG_USESHM=OFF \
    -DVGL_BUILDSTATIC=OFF \
    -DVGL_BUILDFLTK=ON \
    -DCMAKE_CXX_FLAGS="-fPIC"
```
But build ends with the following error:
```
[ 59%] Linking CXX static library ../../lib/libfltk_static.a
[ 59%] Built target fltk_static
make: *** [Makefile:136: all] Error 2
```
Could you please advice me the correct build parameters I need to use?

**Comment by dcommander** [comment]
Add `-DFCONFIG_USESHM=0` to `CMAKE_CXX_FLAGS`.  I'm not sure what you find "too general" about the build documentation.  Most of those flags aren't even needed, so you're making it more complicated than it has to be.  The minimal steps to reproduce our .deb build with the aforementioned feature disabled:

- Download and install the latest stable libjpeg-turbo .deb from https://github.com/libjpeg-turbo/libjpeg-turbo/releases (3.1.0 as of this writing.)
- `git clone https://github.com/VirtualGL/virtualgl.git`
- `cd virtualgl`
- `mkdir build`
- `cd build`
- `cmake -G"Unix Makefiles" -DCMAKE_CXX_FLAGS="-DFCONFIG_USESHM=0" ..`
- `make deb`

**BUILDING.md** essentially says all of that, except for the part about undefining `FCONFIG_USESHM`.

**Comment by sunarowicz** [comment]
I already found the buildscripts, had no clue of them.:o)

But when I run buildvgl with no options, nor specifying branch/tag I get the following errors:
```
-- Build files have been written to: /tmp/vglbuild.7zlQQ9/vgl
Built target dist
/tmp/vglbuild.7zlQQ9
/tmp/vglbuild.7zlQQ9/vgl /tmp/vglbuild.7zlQQ9
Built target dist
pkgscripts/makesrpm: 45: rpmbuild: not found
make[3]: *** [CMakeFiles/srpm.dir/build.make:70: CMakeFiles/srpm] Error 127
make[2]: *** [CMakeFiles/Makefile2:329: CMakeFiles/srpm.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:336: CMakeFiles/srpm.dir/rule] Error 2
make: *** [Makefile:182: srpm] Error 2
```

**Comment by dcommander** [comment]
@sunarowicz Do not use the build scripts.  Use the procedure I posted above.  The build scripts are only used when generating official VirtualGL packages for distribution.  They are not for end users.

As I indicated above, running VirtualGL on a phone in a chroot environment is not even remotely supported.  If you want to do unsupported things, then you have to support yourself.  You can't reasonably expect me to guide you through something that I have never even done myself.  I don't know why the issue occurs, but I have provided a way to work around it.  That's the limit of what I can provide.

**Comment by sunarowicz** [comment]
> @sunarowicz Do not use the build scripts. Use the procedure I posted above. The build scripts are only used when generating official VirtualGL packages for distribution. They are not for end users.

OK, thx for explaining that to me. 

> As I indicated above, running VirtualGL on a phone in a chroot environment is not even remotely supported. If you want to do unsupported things, then you have to support yourself. You can't reasonably expect me to guide you through something that I have never even done myself. I don't know why the issue occurs, but I have provided a way to work around it. That's the limit of what I can provide.

Yeah, I'm aware of that. That's why I was asking @Heasterian in my first post. Anyway, thx for your support and kicking me into (hopefully) right direction. I appreciate that!

**Comment by sunarowicz** [comment]
Just for the record: I succeed to build, but had to change cmake like this:
`cmake -G"Unix Makefiles" -DFCONFIG_USESHM=OFF ..
`
otherwise I got build error.

Built version didn't solved the issue though.

**Comment by dcommander** [comment]
Please learn the difference between a CMake variable and a compile-time macro.
