### ISSUE TITLE
failed to create drawable with amdgpu

### ISSUE THREAD

**Issue by ostway** [VirtualGL/virtualgl#149]
[ ~]$ vglrun +v +tr glxgears
[VGL] NOTICE: Added /usr/lib to LD_LIBRARY_PATH
[VGL] Shared memory segment ID for vglconfig: 393237
[VGL] VirtualGL v2.6.4 64-bit (Build 20200828)
[VGL 0x77604800] XOpenDisplay (name=NULL dpy=0x561a19a6d9a0(:0.0) ) 1.070976 ms
[VGL 0x77604800] glXChooseVisual (dpy=0x561a19a6d9a0(:0.0) screen=0 attrib_list=[0x0004 0x0005 0x0008=0x0001 0x0009=0x0001 0x000a=0x0001 0x000c=0x0001 ] glxattribs=[0x000c=0x0001 0x0005=0x0001 0x0008=0x0001 0x0009=0x0001 0x000a=0x0001 0x8011=0x0001 0x8010=0x0006 ] [VGL] Opening connection to 3D X server :0
[VGL] dlopen (filename=libGLX_mesa.so.0 flag=1 retval=0x561a19a853f0)
[VGL] dlopen (filename=libGLX_mesa.so.0 flag=258 retval=0x561a19a853f0)
[VGL] dlopen (filename=/usr/lib/dri/tls/radeonsi_dri.so flag=258 retval=0x00000000)
[VGL] dlopen (filename=/usr/lib/dri/radeonsi_dri.so flag=258 retval=0x561a19b077b0)
[VGL] dlopen (filename=libGLX_mesa.so.0 flag=258 retval=0x561a19a853f0)
[VGL] dlopen (filename=/usr/lib/dri/tls/radeonsi_dri.so flag=258 retval=0x00000000)
[VGL] dlopen (filename=/usr/lib/dri/radeonsi_dri.so flag=258 retval=0x561a19b077b0)
vis=0x561a19aaa0a0(0x21) config=0x561a19be8390(0xb6) ) 74.404001 ms
[VGL 0x77604800] XCreateWindow (dpy=0x561a19a6d9a0(:0.0) parent=0x000006b2 x=0 y=0 width=300 height=300 depth=24 c_class=1 visual=0x561a19a7c320(0x21) win=0x06a00002 ) 0.003099 ms
[VGL 0x77604800] glXCreateContext (dpy=0x561a19a6d9a0(:0.0) vis=0x561a19aaa0a0(0x21) share_list=0x00000000 direct=1 config=0x561a19be8390(0xb6) ctx=0x561a19ab7ff0 ) 0.840902 ms
[VGL 0x77604800] glXMakeCurrent (dpy=0x561a19a6d9a0(:0.0) drawable=0x06a00002 ctx=0x561a19ab7ff0 
[VGL 0x77604800]   XQueryExtension (dpy=0x561a19a6d9a0(:0.0) name=XVideo *major_opcode=151 *first_event=93 *first_error=155 ) 0.128031 ms
[VGL 0x77604800] 
[VGL 0x77604800]   XQueryExtension (dpy=0x561a19a6d9a0(:0.0) name=XVideo *major_opcode=151 *first_event=93 *first_error=155 ) 0.016928 ms
[VGL 0x77604800] [VGL] Using Pbuffers for rendering
failed to create drawable
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  27 (X_GLXCreatePbuffer)
  Serial number of failed request:  30
  Current serial number in output stream:  32

CPU: Intel Core i7-8700
GPU: Radeon RX 570 Series (POLARIS10, DRM 3.39.0, 5.9.6-arch1-1, LLVM 11.0.0)
mesa 20.2.2-2
xf86-video-amdgpu 19.1.0-2
kernel options: mitigations=off kvm.ignore_msrs=1 iommu=pt intel_iommu=on i915.enable_gvt=1 i915.enable_guc=0 i915.enable_huc=0 i915.modeset=0

When i switch xorg default driver to intel driver and reboot system - vglrun run without problems. what ideas?

**Comment by dcommander** [comment]
Try 2.6.5.

**Comment by ostway** [comment]
> Try 2.6.5.

AWESOME! Works. Big thanks :+1:
