### ISSUE TITLE
method to choose a GPU ID?

### ISSUE THREAD

**Issue by ARtSSt** [VirtualGL/virtualgl#154]
Do you know a method to choose a GPU ID or device in an arbitrary vulkan program that doesn't have an option to choose GPUs? Vulkan only works when device ID is 0 in nvidia-smi now and that was the cause of a bulk of the issues.

We are working from this repo and trying to hack away( I know its not from here put very promising.) https://github.com/ehfd/docker-nvidia-glx-desktop

**Comment by dcommander** [comment]
No, and in fact, that limitation is a big reason why Vulkan can't currently be supported with VirtualGL.

**Comment by ARtSSt** [comment]
Oh well, back to the nvidia wait line I guess. 

Thank you for the quick Reply.

**Comment by ehfd** [comment]
@dcommander https://github.com/aejsmith/vkdevicechooser
Have you considered using this?

**Comment by dcommander** [comment]
@ehfd Refer to https://github.com/VirtualGL/virtualgl/issues/37#issuecomment-461197641.  It's not just a matter of choosing the device.  There are other major technical issues that prevent VirtualGL from supporting Vulkan at the moment.
