### ISSUE TITLE
EGL back end: VMWare Player crashes on VM startup

### ISSUE THREAD

**Issue by Mr-Shibari** [VirtualGL/virtualgl#162]
Hi

There seems to be a problem running VMWare Player with the VirtualGL EGL back end. Running Player works, I see the window in the VNC session but after starting a VM (with 3D support) Player crashes and the VNC session is closed.

I start VMware Player this way: 

**Startup script:**

/opt/TurboVNC/bin/vncserver -geometry 1024x768 -xstartup "start_vmware_player_vnc_script.sh" -fg

**Application script (start_vmware_player_vnc_script.sh):**

export LD_PRELOAD=libvglfaker.so:libdlfaker.so
vglrun +v +tr -d /dev/dri/card1 /usr/bin/vmplayer

Instead of the -d option I also tried with export VGL_DISPLAY=egl, same result.

nVidia Driver Version is: 460.67, VirtualGL version is: v2.6.80 64-bit (Build 20210315)

Here is the TurboVNC/VirtGL log:
[virt_gl_vmware_player.log](https://github.com/VirtualGL/virtualgl/files/6220802/virt_gl_vmware_player.log)

Running Virtualbox this way works fine and I have 3D acceleration. Glmark2 also works fine.

**Comment by dcommander** [comment]
I'll test it.  I just haven't had time yet.

**Comment by dcommander** [comment]
There's a good chance that https://github.com/VirtualGL/virtualgl/commit/9d04f00f965fa75fb0903d9550dea1d1fe950446 fixed this issue.  Can you confirm whether the issue still exists with the latest code in dev or the latest dev pre-release build?

**Comment by Mr-Shibari** [comment]
I've tested it with the new build, this indeed fixed the issue. Thanks for the great work :)
