### ISSUE TITLE
Running OBS Studio results in a black preview screen and black stream output

### ISSUE THREAD

**Issue by bv86** [VirtualGL/virtualgl#166]
Hello,

I'm on arch linux, running the latest OBS version (compiled from source, v 27.0.0.rc2.r65) and with vgl, both the output preview window and the actual output (in streaming, recording or virtual webcam) is black.

It's a NVIDIA T4 GPU running driver version 460.67.

I tried changing settings with VGL_* options but to no avail. 

If I use VGL_LOGO, I do see it properly in the preview output, but I see no video.

In other windows of the program (like source preview or scene preview in studio mode), everything is working fine (I see a VGL logo and everything else that should be there).

Do you have any idea what could be the issue?  No specific errors in the console.

On another computer also running archlinux but with a RTX 3070, I have the same problem but this time I see this error in the console:
error: X Error: BadMatch (invalid parameter attributes), Major opcode: 131, Minor opcode: BadWindow (invalid Window parameter), Serial: 159
error: X Error: BadMatch (invalid parameter attributes), Major opcode: 131, Minor opcode: BadWindow (invalid Window parameter), Serial: 160
...

**Comment by dcommander** [comment]
No idea.  I installed OBS under Ubuntu 20.04, but in order to reproduce the problem, I need to know:
- which 2D X server you are using
- the minimal steps necessary to cause the failure (I have never used OBS and don't have time to learn)
