### ISSUE TITLE
Add a -x to SSHCMD nettest call in vglconnect to work around systemd bug

### ISSUE THREAD

**Issue by paulraines68** [VirtualGL/virtualgl#169]
This is not a bug in vglconnect itself, but a request for simple change to work around a bug in systemd I have found on my CentOS 8 Stream machines where -Y is the default behavior from ssh_config

https://bugzilla.redhat.com/show_bug.cgi?id=1972266

In vglconnect when it makes the nettest call to the remote box (line 121) I request adding a -x option to the SSHCMD line.   It does not appear that X forwarding is needed on that call.

**Comment by dcommander** [comment]
Please clarify. How does vglconnect fail if that argument is not specified?

**Comment by paulraines68** [comment]
Running 'vglconnect -s' to a CentOS 8 Stream box will just hang at "Making preliminary SSH connection to find a free port on the server" forever.
