### ISSUE TITLE
OGLOED mode support

### ISSUE THREAD

**Issue by NickDoom-IDKFA** [VirtualGL/virtualgl#170]
Can you add a "reversed mode" support? I call it "OpenGL On External Device" (OGLOED). It's nearly the same as VirtualGL, but in opposite direction: user has a laptop with Linux and some GPU-heavy applications installed. VirtualGL is also installed on the laptop, and configured to operate in OGLOED mode: it means, interaction with the X-server gets splitted into "OpenGL commands" and "other operations" (like VirtualGL usually does), but OpenGL gets forwarded to a nearest "OGLOED server" (a tiny game-like application without special system permissions which gets incoming OpenGL commands via a gigabit ethernet and draws an OpenGL window; you probably don't even have to bother sending the image back for basic support, because using the server's own display is OK for me), which runs on a GPU-powerful device.
In other words, OGLOED mode is "filtering OpenGL and forcefully sending it via LAN to a rendering server, even if user works locally (X-server works on the same laptop)", instead of common VirtualGL operation "filtering OpenGL and forcefully executing it locally, even if user works remotelly from a thin client/X-server".
Of course, in some cases OGLOED mode is useless because fully-functional X-server (not an "OGLOED server") can be executed on that "nearest powerful device" and simply provide X-server capabilities to an application running on the laptop (operating even without VirtualGL). Unfortunatelly, in my case most of those devices are proprietary "black boxes" which I can't configure at all — a simple "game-like application" is the best I can run, and all I hope to do is to make the device appear on the laptop as an additional "openGL-only" video card.
Of course, I can't ask for writing "OGLOED servers" for every platform in the world — making a basic linux version will be enough, making an Android port (yes, this so-called OS is installed on "GPU-powerful devices" sometimes) will be awesome (I hope Android OpenGL is compatible enough, however… #66?) I also afraid if it'll require special support on the application side (which is also a "black box").

**Comment by dcommander** [comment]
It sounds like you would need to intercept and forward all of OpenGL, not just the GLX commands that VirtualGL intercepts in order to redirect the rendering contexts. For reasons described in the Background article on VirtualGL.org, intercepting all of OpenGL is a non-starter. VirtualGL is specifically designed not to do that, and such a full OpenGL interposer is far beyond the scope of what I could support.
