### ISSUE TITLE
webots: blinking vgl, some times

### ISSUE THREAD

**Issue by juju2013** [VirtualGL/virtualgl#172]
Application: webots R2021a (https://www.cyberbotics.com/)
VirtualGL: 2.6.90
TurboVNC: 2.2.6
Container OS: Ubuntu 18.04.5 LTS
Host OS: Centos 7
GPU: Tesla M2090, driver version: 390.116

When webots runs simulations, some run all good, but some have the main display (vgl window) blinking. Screen recorded example:  https://video.fbxl.net/videos/watch/3389fa83-c31e-4cc4-a861-805e94b16a59

By trial and error, it looks like that wired behavior is linked to some "robots" (PROTO Nodes/robots), but not all of them; in the same simulation, adding some robots will cause blinking, remove them and add other robots and the simulation will run OK.

Here's a trace output of a (almost) empty simulation: http://dl.free.fr/lH4IZIt0F

The same plus a Boston Dynamics dog (screen recorded one): http://dl.free.fr/wl8bbqSMD

Command to lauch webots: `vglrun +v  -d /dev/dri/card1 webots`

Docker compose file:

>   webots:
>     container_name: webots
>     shm_size: 2G
>     image: webots
>     runtime: nvidia
>     privileged: true
>     environment:
>       - NVIDIA_VISIBLE_DEVICES=all
>     networks:
>       dockernet:
>         ipv4_address: 10.99.0.33
>     volumes:
>       - /home/xxx/webots/:/data/
>       - ./init.sh:/init.sh
>       - ./xorg.conf:/etc/X11/xorg.conf
>     devices:
>       - "/dev/dri"
>       - "/dev/vga_arbiter"
>       - "/dev/nvidia0"
>       - "/dev/nvidia1"
>       - "/dev/nvidiactl"
>       - "/dev/nvidia-modeset"
>       - "/dev/nvidia-uvm"
>       - "/dev/nvidia-uvm-tools"
>       - "/dev/fb0"
>     command:
>       /init.sh

**Comment by dcommander** [comment]
Please provide more specific instructions regarding how to download and launch the appropriate Docker container with this application.  The Ubuntu 18.04 tarball does not work on CentOS 7.

**Comment by dcommander** [comment]
Reproduced.  Investigating.  This issue is specific to the EGL back end, which is not surprising.

**Comment by dcommander** [comment]
In the process of investigating this issue, I discovered several other issues with the EGL back end and fixed those, but I have yet to find the cause of this issue.  Since I have very limited resources to work on the EGL back end, it may take a while for this issue to get fixed.  Please be patient.

**Comment by LeehanLee** [comment]
I found that seems only if I launched a robot which included webots/camera.h and used the camera related API, the main display (vgl window) blinking.
![image](https://user-images.githubusercontent.com/14244974/167348183-6f06234e-9fe6-4e35-bfa5-33688650b62a.png)
![image](https://user-images.githubusercontent.com/14244974/167348220-0c8c9294-920c-4b9d-ab5e-d64a641ca6fd.png)

https://user-images.githubusercontent.com/14244974/167348878-1bcc2b42-ba57-4c61-82d1-f0e56ee8370b.mp4


if I comment out these camera related code and rebuild the project, the blinking disappears:

https://user-images.githubusercontent.com/14244974/167350065-14a3d3db-5bb2-4ec9-8486-037b9fe2ef72.mp4

Don't know how to solve this issue.

**Comment by dcommander** [comment]
@LeehanLee That is a good clue.  I reproduced the issue, and it is almost certainly a bug in VGL, but I have thus far been unable to find the bug. Now that I know that it is specific to one mode of operation, I can hopefully look at the application source code and figure out what that mode of operation does at the OpenGL level.

**Comment by dcommander** [comment]
I have spent more hours trying to diagnose this, including comparing the apitrace output with and without cameras enabled.  Unfortunately I am still at a loss.

**Comment by LeehanLee** [comment]
I found the description of the Webots function "wb_camera_enable" here:
https://www.cyberbotics.com/doc/reference/camera#wb_camera_enable
![image](https://user-images.githubusercontent.com/14244974/174434075-7d89b407-3e0a-4a77-8f4d-3cac698d8082.png)

> The wb_camera_enable function allows the user to enable a camera. Once the camera is enabled, it will copy images from GPU memory to CPU memory at each time step, regardless of wb_camera_get_image calls.
> The sampling_period argument specifies the sampling period of the sensor and is expressed in milliseconds. Note that the first measurement will be available only after the first sampling period elapsed.

you can see from the above screenshot, I changed the second parameter "sampling_period" to "50 * time_step"(which was "2 * time_step" at the beginning), and then I found that the blinking frequency in the rendering area was slowed down:
https://user-images.githubusercontent.com/14244974/174434355-93698d47-2356-4639-aaf5-244735b3955b.mp4

I'm not sure if this could help you to diagnose this issue.

**Comment by dcommander** [comment]
That is a good clue. I’ll see if I can find where in the code it copies the image.

**Comment by dcommander** [comment]
I am now able to build Webots from source and get an OpenGL API trace from it, both with and without cameras enabled.  Unfortunately, it hasn't revealed any obvious issues, so I am still clueless.  It still isn't clear exactly how enabling cameras changes the OpenGL call sequence.  I have tried to add print statements to the code to understand the mechanism by which that happens, but so far it hasn't been revealing.  Unfortunately I have to shelve this yet again, as I don't have any more time right now to pursue it.
