### ISSUE TITLE
VirtualGL would not work for non-root users. Could not open display

### ISSUE THREAD

**Issue by aniqueakhtar** [VirtualGL/virtualgl#173]
I installed VirtualGL in our server using the root user. this server has Nvidia GPUs in the machine that other users use.
Ubuntu 18.04.5 LTS
TurboVNC version: 2.2.6
VirtualGL version: 3.0beta1

Configuration settings are set as:
n/n/Y

This is because with (Y/Y/Y) settings, the non-root users were not able to access 'nvidia-smi'.
I have added the users in "vglusers" groups. But still not able to do anything.

I am using TurboVNC to connect to this server. When I run the server on the root user, I am able to use the viewer. However, when I start the server using a non-root user, the Viewer shows a black screen.

Looking into this, I figured the error should be with the VirtualGL and not with the TurboVNC.

As a root user, I tried the three sanity checks.
```
xauth merge /etc/opt/VirtualGL/vgl_xauth_key
xdpyinfo -display :0
/opt/VirtualGL/bin/glxinfo -display :0 -c
```
I did not restrict 3D X server access.
As a root user, I am unable to run the first sanity check:
``xauth: (argv):1:  merge:  unable to open file /etc/opt/VirtualGL/vgl_xauth_key``

However, the 2nd and 3rd sanity check gives me output.

Everything with TurboVNC seems to be working well with the root user.

However, with the non-root users I am unable to run any of the sanity checks. I get this error:
```
No protocol specified
xdpyinfo:  unable to open display ":0".
```

Similarly, this command works as a root user but does not work as a non-root user:
``/opt/VirtualGL/bin/glxspheres64``

I have tried this with both lightdm as well as gdm as default display manager with the same issues.

How can I go about getting the non-root users to be able to run VirtualGL?

Thanks

**Comment by dcommander** [comment]
Your GPU device permissions are almost certainly the culprit.  After you run `vglserver_config`, you may need to reboot the machine in order for the new device permissions to take effect.  If that still doesn't work, then `ls -l /dev/dri` and verify whether the permissions are as you expect.

**Comment by dcommander** [comment]
@aniqueakhtar Did you check the device permissions as suggested above?

**Comment by dcommander** [comment]
Closing due to lack of user response.
