### ISSUE TITLE
Recent versions of Google Chrome do not enable GPU acceleration when using VirtualGL

### ISSUE THREAD

**Issue by dcommander** [VirtualGL/virtualgl#177]
For starters, it is necessary to pass `--use-gl=desktop` on the Chrome command line to tell Chrome to use GLX rather than EGL/X11 (refer to #66.)  However, the GPU process subsequently fails with various error messages from crashpad:

```
[1021/173950.725831:ERROR:process_memory_range.cc(86)] read out of range
[1021/173950.725923:ERROR:elf_image_reader.cc(602)] missing nul-terminator
[1021/173950.731904:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[1021/173950.731985:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
[25048:25048:1021/173950.848186:ERROR:gpu_process_host.cc(956)] GPU process exited unexpectedly: exit_code=11
```

I am not 100% sure that the crashpad errors are the source of the ultimate GPU process failure.  I just know that those errors don't occur when Chrome is executed without VirtualGL on the 3D X server.  An examination of the Chrome source code doesn't reveal any obvious way to disable crashpad.

Passing `-nodl` to `vglrun` makes the crashpad errors go away, but then we're back to a "classic" incompatibility between Chrome's GPU sandbox and VirtualGL:

```
[25520:25520:1021/174239.045369:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

Chrome doesn't like that VirtualGL attached an additional thread (the transport thread) to the process.  The sandbox classes provide a switch to allow multiple threads, but Chrome doesn't appear to expose that switch to the end user.  Traditionally, it has been necessary to pass `--disable-gpu-sandbox` to Chrome in order to work around that issue, but that command-line switch no longer works with recent versions of Chrome.  (An examination of the source code reveals that the GPU sandbox is now force-enabled after the command-line switch is parsed.)

It would be theoretically possible to disable the transport thread in VirtualGL if `VGL_SYNC=1`, which may provide a workaround for Chrome.  The workaround would only be viable for X proxy environments, however.

**Comment by dcommander** [comment]
I believe I have a better understanding of the problem.  It appears as if Chrome is using the bare-metal XCB API in order to bootstrap certain GLX functions.  VirtualGL's support of XCB is basically the minimum necessary to make Qt5 work.  Supporting the entire [XCB-GLX API](https://xcb.freedesktop.org/manual/group__XCB__Glx__API.html) would be daunting.  It appears as if EGL/X11 support (#66) is the path of least resistance here.

**Comment by dcommander** [comment]
Fixed with the EGL/X11 front end in https://github.com/VirtualGL/virtualgl/commit/21cc496a678aed60e7a9886d08dfe5d23eb9ae37.  Chrome can now be run using
```
vglrun -d {path_to_DRI_device} /usr/bin/google-chrome --disable-seccomp-filter-sandbox
```

**Comment by dcommander** [comment]
For anyone stumbling upon this issue, https://github.com/VirtualGL/virtualgl/issues/228#issuecomment-1458759288 describes the results of my testing with the latest Chrome/Chromium releases using VirtualGL 3.0.2 and 3.1 post-beta.  tl;dr: VirtualGL 3.1 (which is currently in beta) and EGL/X11 are necessary in order to enable GPU acceleration with any recent versions of Chrome/Chromium, and you must use the exact application recipe listed in the VirtualGL 3.1 User's Guide.

**Comment by vlrevolution** [comment]
> For anyone stumbling upon this issue, [#228 (comment)](https://github.com/VirtualGL/virtualgl/issues/228#issuecomment-1458759288) describes the results of my testing with the latest Chrome/Chromium releases using VirtualGL 3.0.2 and 3.1 post-beta. tl;dr: VirtualGL 3.1 (which is currently in beta) and EGL/X11 are necessary in order to enable GPU acceleration with any recent versions of Chrome/Chromium, and you must use the exact application recipe listed in the VirtualGL 3.1 User's Guide.

Could you point me to the exact application recipe required or otherwise tell me what to do to get chroem working in VirtualGL?

**Comment by dcommander** [comment]
The recipe that works with Chrome v128 and earlier is in the VirtualGL User's Guide. Referring to #264, that recipe does not work with Chrome v129 and later. I have not yet confirmed a recipe for v129 and later, but another user noted that replacing `--use-gl=egl` with `--use-angle=gl-egl` worked for them. Recent Chrome releases use Vulkan by default, and when using nVidia's proprietary drivers, Vulkan does something VirtualGL-like when it is running in an X proxy environment. I have no idea whether that works in a Docker container, however.

**Comment by vlrevolution** [comment]
Is that recipe to be used with VirtualLGL 3.1.1?

**Comment by dcommander** [comment]
This issue was for an older version of Chrome, and the existing recipe works with that version, which is why this issue was closed as fixed. Please use #265 to discuss issues with Chrome v129+.
