### ISSUE TITLE
VDI w/NVIDIA Tesla M60, /dev/dri/cardX is not valid, but plain egl works

### ISSUE THREAD

**Issue by karlkleinpaste** [VirtualGL/virtualgl#184]
VMware VDI, Centos7, virtualized Tesla M60, driver **450.102.04**. 
```
$ lspci | egrep '3D|VGA'
00:0f.0 VGA compatible controller: VMware SVGA II Adapter
02:02.0 VGA compatible controller: NVIDIA Corporation GM204GL [Tesla M60] (rev a1)
$ ls -l /dev/dri/c*
crw-rw-rw-+ 1 root root 226, 0 Dec  2 08:19 /dev/dri/card0
crw-rw-rw-+ 1 root root 226, 1 Dec  2 08:19 /dev/dri/card1
$ eglinfo /dev/dri/card0 | head -4
Error: invalid EGL device
$ eglinfo /dev/dri/card1 | head -4
Error: invalid EGL device
$ eglinfo egl | head -4
device: egl
EGL client APIs string: OpenGL_ES OpenGL
EGL vendor string: NVIDIA
EGL version string: 1.5
```
In regular use:
```
$ VGL_VERBOSE=1 VGL_DISPLAY=/dev/dri/card1 glxgears
[VGL] Shared memory segment ID for vglconfig: 2359361
[VGL] VirtualGL v3.0 64-bit (Build 20211119)
[VGL] Opening EGL device /dev/dri/card1
[VGL] ERROR: in init3D--
[VGL]    219: Invalid EGL device
```
But glxgears works with VGL_DISPLAY=egl.
For comparison, ordinary real hardware machine, Centos8, regular Quadro M4000, driver **495**.
```
$ lspci | egrep '3D|VGA'
03:00.0 VGA compatible controller: NVIDIA Corporation GM204GL [Quadro M4000] (rev a1)
$ ls -l /dev/dri/c*
crw-rw-rw-+ 1 root root 226, 0 Dec  6 13:06 /dev/dri/card0
$ eglinfo /dev/dri/card0 | head -4
device: /dev/dri/card0
EGL client APIs string: OpenGL_ES OpenGL
EGL vendor string: NVIDIA
EGL version string: 1.5
$ eglinfo egl | head -4
device: egl
EGL client APIs string: OpenGL_ES OpenGL
EGL vendor string: NVIDIA
EGL version string: 1.5
$ VGL_DISPLAY=/dev/dri/card0 glxgears -info | grep -v EXT
GL_RENDERER   = Quadro M4000/PCIe/SSE2
GL_VERSION    = 4.6.0 NVIDIA 495.29.05
GL_VENDOR     = NVIDIA Corporation
VisualID 33, 0x21
12766 frames in 5.0 seconds = 2553.031 FPS

```
Bug in driver 450? Bug in EGL handling for driver 450?
I can't update VDI's driver, as it's constrained by IT's matched deployment in the ESXi server's support.

**Comment by dcommander** [comment]
`eglinfo` accesses the DRI devices in the same way that VirtualGL does, so if `eglinfo egl` works, that suggests that `VGL_DEVICE=egl` should work. As to why the specific DRI devices don’t work, I have no idea. Perhaps the user account does not have appropriate permissions for the matching **/dev/dri/render*** devices? Did you run `vglserver_config` in the container?

**Comment by karlkleinpaste** [comment]
OK, so that was interesting. /dev/dri/cardX were 666, but /dev/dri/render* were 660. I don't know how that happened, on just that 1 machine. chmod'd, and it's fine now when specifying /dev/dri/card1. Evident cockpit error of some kind, but I can't even say whether it was me or someone else using the VDI.
