### ISSUE TITLE
MATLAB fails with EGL back end

### ISSUE THREAD

**Issue by dcommander** [VirtualGL/virtualgl#187]
Users report that MATLAB does not work properly with the EGL back end.

**Comment by dcommander** [comment]
@nathankidd Have you observed any issues with MATLAB and the EGL back end?

**Comment by nathankidd** [comment]
Sadly I've not had opportunity to even look at the EGL side of things.  I'll ask someone to try it.

**Comment by nathankidd** [comment]
Colleague tried basic usage and found no issue to render a simple 3D chart.  But _MATLAB does not work properly_ is pretty vague.

- MATLAB 9.12.0.1975300 (R2022a) Update 3
- CentOS 7
- `rendererinfo(gca)` reports
 
>   GraphicsRenderer: 'OpenGL Hardware'
>               Vendor: 'NVIDIA Corporation'
>              Version: '4.6.0 NVIDIA 460.73.01'
>       RendererDevice: 'Quadro K4200/PCIe/SSE2'

- VGL reports

> [VGL] VirtualGL v3.0.1 64-bit (Build 20220516)
> [VGL] Opening EGL device egl

- Caveats
  - VGL_LOGO=1 has no effect in EGL or GLX mode when rendering below image.  Which makes one wonder if this is even OpenGL rendered at all.  This is the same model that was crashing with the missing fbconfig in that other issue, so my best theory is it _is_ OpenGL, but does internal clipping or something to remove the logo part. 
![image](https://user-images.githubusercontent.com/6314723/179254053-15e149a6-6996-41eb-bb11-ea0338a102eb.png)

**Comment by dcommander** [comment]
`VGL_LOGO` will only work if the application uses `glXSwapBuffers()` to display the rendered frame to the screen (or `glFinish()` and sometimes `glFlush()` if the application is doing front-buffer rendering, but that is uncommon these days.)  If the application is using some other mechanism to display the rendered frame, then `VGL_LOGO` will have no effect.  I have seen this with a few modern applications, some of which are implementing their own off-screen rendering mechanism using FBOs.

**Comment by dcommander** [comment]
Another way to determine whether VirtualGL is active is to enable tracing `vglrun +tr` and see if any OpenGL or GLX commands show up in the trace log as you rotate the plot.

**Comment by nathankidd** [comment]
I actually have a trace here.  It has, e.g.

> [VGL 0xd8839700] glXMakeContextCurrent (dpy=0x7f9ff032a910(:3) draw=0x02000002 read=0x02000002 ctx=0x7f9ff09aaee1 config=0x7f9ff0349300(0x11) draw=0x00000001 read=0x00000001 renderer=Quadro K4200/PCIe/SSE2 ) 4.998922 ms

Though I can't correlate that with actual time model was drawn.  Without further details of _does not work properly_ I'm going to say, _does work properly_.
