### ISSUE TITLE
How I can compile virtualgl with lib32 binaries

### ISSUE THREAD

**Issue by romanlex** [VirtualGL/virtualgl#19]
Sorry for my bad english.
Hello, how I can compile with lib32 binaries.
In the next topic https://github.com/VirtualGL/virtualgl/issues/16 recommended manualy recompile virtualgl package, but for bumblebee needed lib32-virtualgl library.
I try this command:
```
export CFLAGS=-m32
export CXXFLAGS=-m32
export LDFLAGS=-m32
sudo cmake -DCMAKE_INSTALL_PREFIX=/usr/share -DTJPEG_INCLUDE_DIR=/usr/include -DTJPEG_LIBRARY=/usr/lib/libturbojpeg.so
```
But lib32 not installed

**Comment by NecroKote** [comment]
@romanlex, i assume you also use ArchLinux ? If so, please check my comment in #16 thread. I've provided trick, that fixed compilation for me.
