### ISSUE TITLE
Latest dev branch fails to build

### ISSUE THREAD

**Issue by alou-S** [VirtualGL/virtualgl#190]
#### System Info:
OS : Arch Linux
Did I install all the required build dependancies: Yes

#### Bug
Latest dev branch fails to build and gives out the following error during build: https://gist.github.com/alou-S/4ef0ab9ea80bed09037db50cd97fd69a

**Comment by alou-S** [comment]
@dcommander Just a reminder to check the comments of the gist where I have replied to you and probably reply to that here.

**Comment by alou-S** [comment]
As shown in the log in the gist the error `FAILED: server/CMakeFiles/eglxfakerut.dir/eglxfakerut.cpp.o` is related to the file in `server/eglxfakerut.cpp`.

You have stated in the comment of the gist to add `#include<X11/Xlib.h>` to `server/eglxfakerut.cpp` but it is already in said file.
![ss](https://user-images.githubusercontent.com/73123610/149988344-50da4b82-b01b-4b7d-8cc7-7c47010ef7b0.PNG)

As you have said to add the same to `eglxspheres.c` I have added it to `demos/eglxspheres.c` and it does not fix the issue.

**Comment by dcommander** [comment]
OK, sorry.  My mistake.  Well, then I have no idea why it is failing.  Arch is not officially supported by this project, and I do not have it available for testing, so you'll need to figure out why the build fails on that platform and not any other.

**Comment by dcommander** [comment]
Actually, perhaps **eglxfakerut.cpp** needs `#include <X11/Xutil.h>`.  Can you try that?

**Comment by alou-S** [comment]
As on the topic of Arch not being supported, The build fails when I tested on a Debian environment. I'll be testing adding `Xutil.h` in a moment

**Comment by alou-S** [comment]
Yup added `#include <X11/Xutil.h>` and the build is successful. Thanks for the help. Also please if you could make the changes in the repository as soon as possible.
