### ISSUE TITLE
VirtualGL-2.4/server/fakerut.cpp:517: possible bad if ?

### ISSUE THREAD

**Issue by dcb314** [VirtualGL/virtualgl#2]
VirtualGL-2.4/server/fakerut.cpp:517]: (warning) Opposite conditions in nested 'if' blocks lead to a dead code block.

           if(!stereo)
            {
                // ...
                checkWindowColor(win1, clr.bits(-2), ci);
                if(stereo)

**Comment by dcommander** [comment]
The "if(!stereo)" block is a place-holder, and the comment describes why it's there.  If at some point we can figure out why the block doesn't work with stereo on nVidia hardware, the if statement will be removed.
