### ISSUE TITLE
sddm now(?) uses /etc/sddm/Xsetup

### ISSUE THREAD

**Issue by Micket** [VirtualGL/virtualgl#200]
I just spent a frustratingly long time slowly working my up to the observation that `sddm` (at least when packaged for EPEL8) has decided to move Xsetup script to a new location which `vglserver_config`  doesn't know about

Worse yet; old location is still provided, so, everything looks correct
```
# rpm -ql sddm | grep Xsetup
/etc/sddm/Xsetup
/usr/share/sddm/scripts/Xsetup
```

```
# cat /usr/share/sddm/scripts/README.scripts 
This scripts dir contains only samples, but are generally not used directly.
In practice, sddm runtime uses items under /etc/sddm by default
```
and the configuration does indeed point there by default
```
# grep Xsetup /etc/sddm.conf
#DisplayCommand=/etc/sddm/Xsetup
```

Perhaps the setup script wants to add this new path as well?

**Comment by dcommander** [comment]
I’ll look into it. SDDM doesn’t get tested very frequently by the VGL community. I will have to set it up and see what exactly it is doing.

**Comment by Micket** [comment]
I forgot to add; I can confirm that it just simply worked when i copied the Xsetup file over (or switch the sddm configuration over to the old location)
(I chose sddm because there were packaging issues with the lightdm rpms; missing deps that i didn't want to deal with)

**Comment by dcommander** [comment]
Should be fixed now
