### ISSUE TITLE
Wine crashes on 32-bit installation

### ISSUE THREAD

**Issue by dnord** [VirtualGL/virtualgl#21]
I was testing VirtualGL with Xephyr and on 64-bit machines it worked great, but on 32-bit installations while native games worked, every single Wine game crashed with errors about 0x00000000 address (something like EIP=0x00000000). Example of such message: 
>A violation in 00000000 occured at 00000000 with Read.

Tested on Ubuntu 16.04 (64-bit), Ubuntu 14.04 (32-bit, wine 1.7, VirtualGL 2.5) and Debian 9 (32-bit, wine 1.8, VirtualGL 2.5).

**Comment by dcommander** [comment]
Can this be reproduced with an application that is either open source or freely available to download?  For instance, WGLspheres in the 32-bit VirtualGL-Utils package? (available in the Files area on our SourceForge page.)

**Comment by dnord** [comment]
Yes, wglspheres.exe crashes too on 32-bit machine with
>wine: Unhandled page fault on execute access to 0x00000000 at address (nil) (thread 0009), starting debugger...

**Comment by dcommander** [comment]
Reproduced.  Apparently this was a regression between VGL 2.3.3 and 2.4.  Investigating.

**Comment by dnord** [comment]
Thank you very much for so fast fix! It's working now.
