### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by Tachi107** [VirtualGL/virtualgl#210]
Hi! I'm looking into packaging virtualgl for Debian (i.e. making it available in its main repositories), and I've noticed a few issues in the CMake build scripts. I'd like to send some patches, but before putting significant time into them I'd like to ask a few questions:

- You currently require CMake 2.8.12; would it be possible to raise the requirement?
- Is it there a particular reason why the build script looks for libjpeg-turbo in /opt, and doesn't use neither the pkg-config file nor the CMake Config file provided by the library?

Thanks for your work on VirtualGL!

Edit: VirtualGL already requires CMake 3.10 to build the EGL backend. Bumping the overall minimum required version to 3.10 would allow using `FindOpenGL`'s imported targets tree-wide, and clean up the CMake script significantly.

**Comment by dcommander** [comment]
> * Is it there a particular reason why the build script looks for libjpeg-turbo in /opt, and doesn't use neither the pkg-config file nor the CMake Config file provided by the library?

Historical Reasons (TM).  When libjpeg-turbo first came on the scene in 2010, VirtualGL had been around for six years already and had a lot more traction than libjpeg-turbo had.  libjpeg-turbo was originally introduced as a drop-in replacement for libjpeg v6b, the idea being that you could install the official libjpeg-turbo packages (which placed the libraries under **/opt/libjpeg-turbo**) and manipulate `LD_LIBRARY_PATH` to use libjpeg-turbo, rather than the system's unaccelerated implementation of libjpeg v6b, at run time.  libjpeg-turbo is now available in almost all Linux distributions, but it isn't guaranteed that any given Linux distribution will contain the latest libjpeg-turbo bits or that any given distribution will ship the TurboJPEG API library.  Thus, the most painless way to guarantee a successful build of VirtualGL is still to install the libjpeg-turbo SDK, which is why the VGL build system looks for it first.  Failing to find it, however, it will then look for libjpeg-turbo in the system library paths.

My philosophy of open source software is that, if I release a binary package, I want to make it easy and intuitive for users to reproduce that binary package.  Thus, the default build modes in VirtualGL and TurboVNC will, for the most part, generate builds that are very similar to our official builds, and since the official builds are cross-distribution, the default build modes are cross-distribution.  That's yet another reason why VGL looks for libjpeg-turbo under **/opt/libjpeg-turbo** by default.  You have to set CMake variables in order to make a distro-specific VGL or TurboVNC build, and that is by design.

The pkg-config files for libjpeg-turbo were introduced in libjpeg-turbo 1.5 (2016), and the CMake config files were introduced in libjpeg-turbo 2.1 (2021).  The CMake config files are probably still too new to require just yet, but I would be open to a patch that optionally uses the libjpeg-turbo pkg-config files if a certain CMake variable is specified.

> Edit: VirtualGL already requires CMake 3.10 to build the EGL backend. Bumping the overall minimum required version to 3.10 would allow using `FindOpenGL`'s imported targets tree-wide, and clean up the CMake script significantly.

Thanks for the clarification.  I am open to making that change.  Can you provide more details about what could be cleaned up?

**Comment by Tachi107** [comment]
Thanks for the detailed comment! It's always interesting to learn a bit about the history of a project :)

> it isn't guaranteed that any given Linux distribution will contain the latest libjpeg-turbo bits or that any given distribution will ship the TurboJPEG API library. Thus, the most painless way to guarantee a successful build of VirtualGL is still to install the libjpeg-turbo SDK, which is why the VGL build system looks for it first. Failing to find it, however, it will then look for libjpeg-turbo in the system library paths.
> 
> My philosophy of open source software is that, if I release a binary package, I want to make it easy and intuitive for users to reproduce that binary package. Thus, the default build modes in VirtualGL and TurboVNC will, for the most part, generate builds that are very similar to our official builds, and since the official builds are cross-distribution, the default build modes are cross-distribution. That's yet another reason why VGL looks for libjpeg-turbo under **/opt/libjpeg-turbo** by default. You have to set CMake variables in order to make a distro-specific VGL or TurboVNC build, and that is by design.

I can see how your rationale for preferring the libjpeg-turbo SDK makes sense, but wouldn't it be simpler for the users building VirtualGL to have it automatically look for the "classic" distro-supplied development files if they don't have the SDK installed?

> The pkg-config files for libjpeg-turbo were introduced in libjpeg-turbo 1.5 (2016), and the CMake config files were introduced in libjpeg-turbo 2.1 (2021). The CMake config files are probably still too new to require just yet, but I would be open to a patch that optionally uses the libjpeg-turbo pkg-config files if a certain CMake variable is specified.

Same as above. I build (and contribute to) a lot of projects as part of my packaging efforts, and I find it way more pleasant when installing the required dependencies and building the project just works, compared to also having to figure out which variables I have to enable to use system libraries. Thus, if reasonable for VirtualGL, I'd prefer to submit a patch that uses whatever is available automatically (if compatible with what's being requested, obviously); for example, the current libjpeg-turbo Find module could be modified like this (pseudo CMake code):

```cmake
# check for the sdk
if (sdk_FOUND)
   # done
endif()

# search the system library using the CMake Config files
find_package(libjpeg-turbo) 
if (libjpeg-turbo_FOUND)
    # done
endif()

# search the system library using pkg-config
find_package(PkgConfig)
pkg_search_module(libturbojpeg IMPORTED_TARGET libturbojpeg)
if (libturbojpeg_FOUND)
    # done
endif()
```
 
> > Edit: VirtualGL already requires CMake 3.10 to build the EGL backend. Bumping the overall minimum required version to 3.10 would allow using `FindOpenGL`'s imported targets tree-wide, and clean up the CMake script significantly.
> 
> Thanks for the clarification. I am open to making that change. Can you provide more details about what could be cleaned up?

Newer CMake versions introduce various idioms that can make CMake code more concise and/or robust. For example, using Imported Targets instead of plain variables allows CMake to check that the referenced targets exist at configure time (as opposed to failing at link time), make it possible to properly propagate transitive dependencies, etc. I'm not really good at explaining CMake stuff, but It'll be clearer when I'll submit the patch :)

**Comment by dcommander** [comment]
Go ahead and submit the patch for all of the above.  I will evaluate it and make more specific comments in the PR.

**Comment by dcommander** [comment]
If you want this to land in 3.0.2, I will need a PR very soon.

**Comment by Tachi107** [comment]
Hi, I'm still working on it. If it won't land in 3.0.2, it's not an issue for me :)

**Comment by dcommander** [comment]
Are you ever going to submit a PR for this?

**Comment by Tachi107** [comment]
Hi, thanks for your message. Unfortunately my priorities have shifted since when I originally opened this issue, and I don't plan to package your (awesome) library, at least for now. Closing. Thanks :)

**Comment by dcommander** [comment]
I am trying to use the libjpeg-turbo CMake package config file, but it doesn't appear to work.  `find_package()` finds the official libjpeg-turbo package with no problem as long as I set `CMAKE_PREFIX_PATH` to **/opt/libjpeg-turbo**, and the targets are successfully imported.  However, any attempt to link with the imported targets, even in the same directory scope, fails.  What am I doing wrong?

**Comment by dcommander** [comment]
I looked into these issues and wanted to add a comment regarding my findings:
- Unfortunately, using imported targets with `FindOpenGL()` is a non-starter at the moment, for two reasons:
    1. On macOS, the only way to link with OpenGL/X11 is to manually override `OPENGL_glu_LIBRARY` and `OPENGL_gl_LIBRARY`.  The `FindOpenGL()` documentation even says as much.
    2. The Faker build uses the `OPENGL_*_LIBRARY` variables for a special purpose.  Thus, using imported targets wouldn't really clean up the build.  It would just replace most (but not all) instances of `${OPENGL_gl_LIBRARY}` with `OpenGL::GL`, most (but not all) instances of `${OPENGL_egl_LIBRARY}` with `OpenGL::EGL`, and all instances of `${OPENGL_glu_LIBRARY}` with `OpenGL::GLU`, and it would remove one of the paths from the `include_directories()` call in the root of the build.  That's not very compelling.
- I experimented quite a bit with changing the FindTurboJPEG script, but most of what I came up with was more complicated without really improving the functionality.
    1. The build system could use the libjpeg-turbo CMake config scripts, if available.  However:
        - Those scripts are only provided by the official libjpeg-turbo v2.1+ SDK and by the MSYS libjpeg-turbo package.  Linux distributions that package libjpeg-turbo v2.1+ don't seem to provide the CMake config scripts, perhaps because they prefer to package the TurboJPEG API library separately or because they don't package the static libraries. 
        - It would be necessary to introduce two new user-definable variables, one (`libjpeg-turbo_ROOT`) that instructs the build system to look for CMake config files in a non-default location and another (`TJPEG_TARGET`) that allows the builder to override the default `libjpeg-turbo::turbojpeg-static` target.  That seems unnecessarily complicated, since `TJPEG_LIBRARY` effectively provides the same capability using a single variable.  Also, it would be confusing to have variables that only apply if the build system is able to find the official libjpeg-turbo SDK
    2. Using pkg-config as a fallback on Un*x systems if the SDK specified by `TJPEG_INCLUDE_DIR` and `TJPEG_LIBRARY` isn't available makes a certain kind of sense, but it doesn't really produce a different result in practice.  In practice, the system-supplied pkg-config scripts for the TurboJPEG API library always set the link library to `turbojpeg`, which is what FindTurboJPEG already does.
    3. It would seemingly make more sense to just use pkg-config all the time and set the defaults appropriately so that it finds the official libjpeg-turbo SDK, if available.  However, there isn't a straightforward way to link with the static TurboJPEG API library when using pkg-config.
    4. At the end of the day, it's just easier to override `TJPEG_INCLUDE_DIR` and `TJPEG_LIBRARY` than to mess with any of that.  I know it's not as elegant, but in this case, more elegance means more complexity, and I don't want more complexity.
