### ISSUE TITLE
Please provide downloads as attachments to Releases on Github

### ISSUE THREAD

**Issue by gdevenyi** [VirtualGL/virtualgl#212]
Download binaries can be attached to releases on Github

https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by dcommander** [comment]
I am well aware of GitHub's file release mechanism.  The reasons why SourceForge is used instead:

1. It provides SSH access, so official builds can be deployed automatically as official releases using a script.
2. It provides comprehensive download statistics for every file and directory.
3. It allows for arbitrary file and directory structures, so a YUM repository can be maintained on SourceForge's file release servers and automatically updated using the aforementioned script.

If GitHub provided all of those things, then I would consider moving the releases to it, but barring that, there are no plans to do so.  Our project predated the existence of GitHub by about four years and predated the popularity of GitHub by about ten years, so we've always used SourceForge for releases.  It would be a pain to move them, and I am not willing to endure that pain unless there is a compelling reason to do so.
