### ISSUE TITLE
Compilation fails of version 3.0.2

### ISSUE THREAD

**Issue by wvalcke** [VirtualGL/virtualgl#217]
usr/bin/ld: /opt/libjpeg-turbo/lib64/libturbojpeg.a(turbojpeg.c.o): relocation R_X86_64_TPOFF32 against `errStr' can not be used when making a shared object; recompile with -fPIC
collect2: error: ld returned 1 exit status

I'm using libjpegturbo version 2.1.3

This error happens during linking with ../lib/libvglfaker.so

**Comment by dcommander** [comment]
Are you using your own build of libjpeg-turbo?  The official libjpeg-turbo SDKs are built with `-fPIC` for precisely this reason.

**Comment by wvalcke** [comment]
Hi

Yes indeed, i used my own build and the default cmake build does NOT add -fPIC to the CFLAGS. I've added this during cmake configuration, now everything compiles as it should.
Thanks for the reply.
