### ISSUE TITLE
No stereo=1 in glxinfo and slower performance with vglrun than without

### ISSUE THREAD

**Issue by joehays** [VirtualGL/virtualgl#234]
I'm trying to setup an Ubuntu 20.04 machine with VirtualGL. I've gone through the steps detailed in,

https://rawcdn.githack.com/VirtualGL/virtualgl/2.6.5/doc/index.html#hd005001

but I'm not seeing performance improvements. I'm connected to the server through a TurboVNC 2.6.5 connection and from a terminal within the TurboVNC I run the following,

`joehays@sedacs19:~$ groups`
`dev sudo docker TVmedia vglusers`

then,

`joehays@sedacs19:~$ /opt/VirtualGL/bin/glxinfo -display :1 -c -v | grep stereo=1`

with an empty output. If I run,

`joehays@sedacs19:~$ /opt/VirtualGL/bin/glxinfo -display :1 -c -v | grep stereo`

all outputs show `stereo=0`.

Additionally,

> joehays@sedacs19:~$ /opt/VirtualGL/bin/glxspheres64 -m
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
GLX FB config ID of window: 0x164 (8/8/8/0)
Visual ID of window: 0x3f7
Context is Direct
OpenGL Renderer: llvmpipe (LLVM 12.0.0, 256 bits)
31.603757 frames/sec - 36.143574 Mpixels/sec
34.743021 frames/sec - 29.963286 Mpixels/sec
37.857260 frames/sec - 28.963833 Mpixels/sec

is faster than,

> joehays@sedacs19:~$ /opt/VirtualGL/bin/vglrun -sp /opt/VirtualGL/bin/glxspheres64 -m
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
GLX FB config ID of window: 0x13d (8/8/8/0)
Visual ID of window: 0x21
Context is Direct
OpenGL Renderer: llvmpipe (LLVM 12.0.0, 256 bits)
27.444947 frames/sec - 31.387359 Mpixels/sec
30.785563 frames/sec - 25.997089 Mpixels/sec
34.532686 frames/sec - 26.420267 Mpixels/sec
33.235152 frames/sec - 25.427550 Mpixels/sec
33.545738 frames/sec - 25.665173 Mpixels/sec

I expected the vglrun glxspheres64 to run faster. 

Any ideas what I might have wrong here?

**Comment by dcommander** [comment]
There is no TurboVNC 2.6.5, but that isn't relevant to the issue.

Why would you assume that stereo is available on Display :1?  That would only be the case if Display :1 were connected to a stereo-capable GPU.

VirtualGL is fundamentally an OpenGL redirector.  It redirects OpenGL rendering away from the X proxy's (TurboVNC's) X display, which is unaccelerated, to either a "3D X server" (a dedicated X server attached to a GPU that all VirtualGL instances share) or an EGL device.  The 3D X server defaults to Display :0.0, but you can change the `VGL_DISPLAY` environment variable to redirect OpenGL rendering elsewhere (including to an EGL device.)  It appears that Display :0.0 in your machine isn't GPU-accelerated, which is why vglrun doesn't accelerate anything.  The clue is that GLXspheres reports "llvmpipe" as the renderer both with and without vglrun.

**Comment by joehays** [comment]
My apologies. It's VirtualGL version 2.6.5 and version TurboVNC 3.0.

I am not very educated on all these remote graphics details. All I'm trying to do is to get Blender sped up on a remote machine that I connect to with TurboVNC. 

>The 3D X server defaults to Display :0.0, but you can change the VGL_DISPLAY environment variable to redirect OpenGL rendering elsewhere (including to an EGL device.) It appears that Display :0.0 in your machine isn't GPU-accelerated, which is why vglrun doesn't accelerate anything. The clue is that GLXspheres reports "llvmpipe" as the renderer both with and without vglrun.

Since I'm remotely connected with TurboVNC (which was an assigned DISPLAY=:1) I have no DISPLAY :0.0. If there is a way to set that up and associate the GPU with a display :0.0... please do tell. 

My apologies if the docs already address this but I tried to follow the directions in the docs linked above and came to the point that I shared in the original posting. Since "llvmpipe" is being used and not a GPU accelerated channel then please help me figure out what I need to do to get the 3D graphics rendered through the GPU and displayed on the TurboVNC desktop.

Thanks.

**Comment by dcommander** [comment]
The 3D X server is the same as the local X server that you would use to log into the machine if you were sitting in front of it. How to set that up is distribution-specific, so the VirtualGL User's Guide assumes that that has already been done. If you don't want to set that up, you can try using an EGL device. You still need to install the driver for your GPU, however.
