### ISSUE TITLE
help with VirtualGL in docker

### ISSUE THREAD

**Issue by sunyi000** [VirtualGL/virtualgl#237]
I have a docker container which uses egl backend  to run an application. 
It works in one k8s cluster but not the other.

the one which is not working outputs an error

`[1295:7:0828/141752.127460:ERROR:command_buffer_proxy_impl.cc(125)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer`

I have no idea why this is happening and how to debug/fix this. Could anyone please help on this?

Thank you very much

**Comment by dcommander** [comment]
I'm the only one who typically responds to these GitHub issues. You might have better luck posting to the VirtualGL-Users Google Group. Unfortunately I have no idea what the issue might be.

**Comment by ehfd** [comment]
https://github.com/selkies-project/docker-nvidia-egl-desktop

I maintain this container. I'm assuming that this is a Chromium error with OpenGL. Probably relate to https://github.com/VirtualGL/virtualgl/issues/229 ?

**Comment by dcommander** [comment]
@ehfd No, the OP clearly said that the application works on one cluster but not another. The Chrome failure is a compatibility issue between VGL and Chrome, and it is not system-specific.

**Comment by ehfd** [comment]
Commented because the error message is much likely from Chromium. Yeah, I guess it isn't a VGL issue.

**Comment by sunyi000** [comment]
Thanks very much @ehfd @dcommander 

The error is from ChimeraX. I suspect it's something to do with the k8s cluster as it runs fine in one cluster but not the other.

I will ask around. Thanks very much
