### ISSUE TITLE
gcc6 compatibility fix.

### ISSUE THREAD

**Issue by bartoszek** [VirtualGL/virtualgl#24]
gcc-6 throws an error while compiling VirtualDrawable.cpp:
`...../virtualgl-git/src/virtualgl/server/VirtualDrawable.cpp:30:41: error: unable to find string literal operator ‘operator""m’ with ‘const char [11]’, ‘long unsigned int’ arguments`
`#define CHECKGL(m) if(glError()) _throw("Could not "m);`
This is due to the new [user defined literals](http://en.cppreference.com/w/cpp/language/user_literal).
Also in fl_draw.cxx `#define min` should be put after `#include <math.h>` as it has this macro undefined.
Fixing those issues results in gcc6 flawless compilation.

**Comment by dcommander** [comment]
Questions:
* Is this a more general compilation issue resulting from gcc6's use of a newer c++ standard?  That is, would this same issue pop up in other c++14 compilers, or is it specific to gcc6?
* Does gcc6 provide a compiler-specific pragma or other means to disable user-defined literals?  Seems like a compatibility minefield to me.  Not sure why they would enable something by default that breaks existing code.
* Is there a simple way to modify the code and make it work (for instance, by inserting a space between the quotation mark and the "m"?  I have no access to gcc6, so I can't test.

**Comment by dcommander** [comment]
Should be fixed in master.  Thanks.

**Comment by pacho2** [comment]
Hi! Is there any new release planned to fix this (and other bugs fixed since February)? Thanks a lot :)

**Comment by dcommander** [comment]
Yes, 2.5.1 is imminent, but I'm working on one last bug report.  Should be out within the next few days.

**Comment by pacho2** [comment]
Thanks!
