### ISSUE TITLE
 virtualgl : Depends: libegl1-mesa:amd64 but it is not installable

### ISSUE THREAD

**Issue by charliez0** [VirtualGL/virtualgl#242]
Can you change the dep so that it don't use obsolete package?

**Comment by dcommander** [comment]
What platform?  It works fine on Ubuntu 22.04 LTS.

**Comment by charliez0** [comment]
23.10

**Comment by charliez0** [comment]
23.10 don't have libegl1 package, manually install one from 23.04 can resolve the problem, but it'd be better if the dependency can change.

**Comment by dcommander** [comment]
But then the VirtualGL package would not work properly on earlier Ubuntu versions. What is the name of the new EGL package that replaces libegl1-mesa?

**Comment by charliez0** [comment]
[libegl1](https://packages.ubuntu.com/focal/libegl1-mesa)

**Comment by charliez0** [comment]
it's libegl1
