### ISSUE TITLE
[Question] does the VirtualGL executable have a version flag/switch?

### ISSUE THREAD

**Issue by MatzFan** [VirtualGL/virtualgl#257]
`vglrun -v` and `vglrun --version` seem to be missing from the help options, am I looking in the wrong place?

My installation is on Linux Bookworm, from your apt repo. Awesome software btw.

**Comment by dcommander** [comment]
No, but that would be easy to implement, since vglrun is generated by CMake.

**Comment by dcommander** [comment]
I just added a `--version` switch to `vglrun`.  For completeness, I should also note that there are some existing, less obvious, ways to obtain the VirtualGL Faker version without using the new `vglrun` switch:
- `/opt/VirtualGL/bin/vglclient -v` (assuming the client is also installed)
- `/opt/VirtualGL/bin/glreadtest -?`
- `vglrun +v /opt/VirtualGL/bin/glxinfo 2>&1 | grep 'VirtualGL v'` (this is the actual Faker version, as reported by the Faker itself)

**Comment by dcommander** [comment]
Another note: `vglrun -v*` is already reserved for disabling verbose mode, so `vglrun -v` or `vglrun -version` will not display the version information.  You have to use two dashes, i.e. `vglrun --version`.
