### ISSUE TITLE
causes issues with display managers (Auth)?

### ISSUE THREAD

**Issue by Clutchnp** [VirtualGL/virtualgl#258]
Distro: Arch  
Graphics: Nvidia (1660 super)
Steps to Reproduce:
1. install virtualgl using pacman
2. run vglserver_config with defaults
3. add user to vglusers group 
4. restart 
```
sddm error 
Aug 12 11:32:31 clutchrig sddm[627]: Auth: sddm-helper exited with 6
Aug 12 11:32:31 clutchrig sddm[627]: Greeter stopped. SDDM::Auth::HelperExitStatus(6)
```
Also I can run sddm without any problems after logging in through tty 
ask me if you need anything else 

EDIT: due to my unability to recover from that system I put a  new arch installation on my system. so I will be unable to  do further testing

**Comment by dcommander** [comment]
Are you using a build of VirtualGL from our official source? I ask that because Arch unfortunately has a history of packaging VirtualGL in incorrect ways that break things.

**Comment by dcommander** [comment]
For future reference, the only change that `vglserver_config` makes to the SDDM configuration is to add an invocation of the `vglgenkey` script to the top of **/etc/sddm/Xsetup** or **/usr/share/sddm/scripts/Xsetup**.  That should break anything, but I will try to reproduce the issue using a newer SDDM code base.  (SDDM doesn't get tested with VirtualGL very much.)

**Comment by dcommander** [comment]
VirtualGL works perfectly fine with SDDM 0.20.0 on Fedora.  I have no way of testing Arch, so I'm not sure what the problem might be.  I would suggest comparing the contents of **/etc/sddm/Xsetup** and **/usr/share/sddm/scripts/Xsetup** from before and after you run `vglserver_config`.  That will ensure that `vglserver_config` is only changing what it is supposed to change.  (On my system, those scripts are empty before I run `vglserver_config`.)  You might also modify **/etc/sddm/Xsetup** and redirect the output of the `vglgenkey` script to a temporary file so you can see whether it is failing somehow, e.g.

```
/opt/VirtualGL/bin/vglgenkey >/tmp/vglgenkey.log 2>&1
```
