### ISSUE TITLE
Chrome 129.0.6668.100 is crashing with --in-process-gpu

### ISSUE THREAD

**Issue by langeschro** [VirtualGL/virtualgl#264]
Since upgrading Chrome from release 126 to 129 I am no longer able to start it with the -in-process-gpu option.

Command Line: `vglrun +tr -d egl google-chrome --in-process-gpu --use-gl=egl`

It still works without --in-process-gpu

OS: Rocky 8.10
GPU: Nvidia Tesla T4
VirtualGL-3.1.1-20240228.x86_64
turbovnc-3.1.2-20240808.x86_64
nvidia-driver-550.90.12-1.el8.x86_64

Last lines of the trace:
`[VGL 0xc15ba600] XQueryExtension (dpy=0x274001c8000(:1) name=MIT-SHM *major_opcode=130 *first_event=65 *first_error=128 ) 0.028849 ms
[VGL 0xc15ba600] XCreateWindow (dpy=0x274001c8000(:1) parent=0x00000534 x=-1 y=-1 width=1 height=1 depth=24 c_class=1 visual=0x27400234000(0x21) win=0x01800003 ) 0.001907 ms
[VGL 0xc15ba600] XCreateWindow (dpy=0x274001c8000(:1) parent=0x00000534 x=0 y=0 width=200 height=200 depth=24 c_class=1 visual=0x27400234000(0x21) win=0x01800006 ) 0.001907 ms
[VGL 0xc15ba600] XCreateWindow (dpy=0x274001c8000(:1) parent=0x01800006 x=-1 y=-1 width=1 height=1 depth=0 c_class=2 visual=0x00000000(0x00) win=0x01800007 ) 0.000000 ms
[VGL] dlopen (filename=/usr/lib64/gio/modules/libdconfsettings.so flag=1 retval=0x27400399900)
[VGL] dlopen (filename=libpci.so.3 flag=1 retval=0x2740039ad00)
[VGL 0x995fa700] XOpenDisplay (name=NULL [VGL] dlopen (filename=libsecret-1.so.0 flag=258dpy=0x274001d0c00(:1) ) 0.516891 ms
[VGL 0x995fa700] XQueryExtension (dpy=0x274001d0c00(:1) name=NV-CONTROL *major_opcode=0 *first_event=0 *first_error=0 ) 0.087023 ms
[VGL 0x995fa700] XCloseDisplay (dpy=0x274001d0c00(:1)  retval=0x2740039ad00)
) 0.890970 ms
[4017:4068:1015/165919.715644:ERROR:gl_factory.cc(98)] Requested GL implementation (gl=egl-gles2,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default)].
[VGL] dlopen (filename=libva.so.2 flag=1 retval=0x00000000)
[VGL] dlopen (filename=/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so flag=1 retval=0x27401b4db00)
[VGL] dlopen (filename=libXcursor.so.1 flag=1 retval=0x2740019f200)
[4017:4163:1015/165919.983885:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[4017:4163:1015/165919.984135:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[4017:4163:1015/165919.984345:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[4017:4068:1015/165919.987531:FATAL:check.cc(360)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[1015/165920.005991:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[1015/165920.006046:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Trace/breakpoint trap (core dumped)
`

Please let me know if you need any further information.

**Comment by langeschro** [comment]
I kind of created this ticket because I was having issues with Firefox (screen glitching) and this seemed to work better in Chrome at first. But even with the older Chrome 126 resizing the browser window was not possible with EGL.

Things seem to work fine in Firefox with the latest VirtualGL stack so far from what I can tell.

**Comment by dcommander** [comment]
No idea.  Referring to https://github.com/VirtualGL/virtualgl/issues/229, making Chrome work with VirtualGL is a lot more complicated than it should be.  It seems like the Chrome developers fundamentally change something every few releases that invalidates the previous VirtualGL workaround, and it requires me to spend many unpaid hours building Chrome from source and instrumenting the code in order to diagnose the problem.  I will not be doing that again unless someone pays me to.

`--use-gl=egl` may not work anymore.  That mode was considered deprecated, so it may now be necessary to use ANGLE, e.g.:

```
VGL_CHROMEHACK=1 vglrun [-d egl] google-chrome --in-process-gpu --use-angle=gl-egl
```

However, you will probably encounter https://issues.chromium.org/issues/326752457 and https://issues.chromium.org/issues/326752458, which haven't been fixed yet.

Chrome uses Vulkan by default, and when using nVidia's proprietary drivers, Vulkan does something VirtualGL-like if it detects that it is running in an X proxy (e.g. Xvnc.)  The only major disadvantage of that vs. VirtualGL is the inability to select a GPU on a multi-GPU system.  Otherwise, it should be possible to get GPU acceleration with Chrome without using VirtualGL, as long as you are using nVidia's drivers.

The Firefox screen glitching issue was fixed in VirtualGL 3.1.1.

**Comment by langeschro** [comment]
Thanks a lot for your reply @dcommander
I can feel your pain, it must be very frustrating to work on fixes for Google Chrome when they don't last very long.

Just wanted to report back that using `--use-angle=gl-egl` works! (Also without `VGL_CHROMEHACK=1`)

It's also possible to resize the browser now with hardware acceleration, wohoo!

I'll make sure that Firefox is set as default browser in our environment.

`Graphics Feature Status
=======================
*   Canvas: Hardware accelerated
*   Canvas out-of-process rasterization: Enabled
*   Direct Rendering Display Compositor: Disabled
*   Compositing: Hardware accelerated
*   Multiple Raster Threads: Enabled
*   OpenGL: Enabled
*   Rasterization: Hardware accelerated
*   Raw Draw: Disabled
*   Skia Graphite: Disabled
*   Video Decode: Hardware accelerated
*   Video Encode: Software only. Hardware acceleration disabled
*   Vulkan: Disabled
*   WebGL: Hardware accelerated
*   WebGL2: Hardware accelerated
*   WebGPU: Disabled
*   WebNN: Disabled`

**Comment by dcommander** [comment]
OK, great.  I'll test that myself and update the application recipe accordingly if I can confirm that `--use-angle=gl-egl` works on my system.

**Comment by dcommander** [comment]
Referring to my long comment under https://issues.chromium.org/issues/326752458, I can confirm that `--use-gl=egl --in-process-gpu` no longer works with Chrome v129+.  Unfortunately, I can't find any other mode that works reliably.  `--use-angle=gl-egl --in-process-gpu`, regardless of the value of `VGL_CHROMEHACK`, causes Chrome to print an error ("[4999:5050:1030/110408.503963:ERROR:gl_surface_egl.cc(391)] No suitable EGL configs found for initialization") at startup, the WebGL/WebGL2 entries under **about:gpu** read "Hardware accelerated but at reduced performance", and WebGL applications sometimes work properly and sometimes hang the browser.

I also note that, when using Chrome without VirtualGL and without any command-line arguments, it does not enable GPU acceleration with nVidia's Vulkan driver in an X proxy environment, even though other Vulkan applications work properly in that environment.  I give up.  Figuring this out would require potentially weeks of building Chrome from source and adding print statements in its graphics stack code (which is many layers deep) to figure out exactly what it's now doing to break VirtualGL.  I can't afford to do that when no one is paying for the labor.  At the moment, all I can do is change the application recipe in the VirtualGL User's Guide to indicate that Chrome v129+ can't be used.

**Comment by dcommander** [comment]
Per above, nVidia's Vulkan implementation does something VirtualGL-like in an X proxy environment, redirecting Vulkan rendering to an off-screen buffer on the GPU and using a swap chain that reads back the rendered pixels from the GPU and composites them into the appropriate X window.  In my testing, passing `--use-angle=vulkan` to Chrome (without VirtualGL) makes it work with nVidia's Vulkan implementation.  WebGL applications appear to be accelerated, and `nvidia-smi` reports that the GPU is used.  However, **about:gpu** reports that Compositing is "Software only", and WebGL/WebGL2 are "Hardware accelerated but at reduced performance".  Maybe that's a function of nVidia's custom swap chain.  Anyhow, it seems like a possible workaround.  Note that, when using non-nVidia GPUs, another workaround is simply to enable DRI3 in TurboVNC 3.2 and later, which allows Vulkan applications to run with GPU acceleration when using Mesa-based drivers.

**Comment by dcommander** [comment]
b0180f7a6d7173cf059ef4a66c369a11c8f9184b extends `VGL_CHROMEHACK` to the GLX interposer, which allows you to run Chrome with:
```
VGL_CHROMEHACK=1 vglrun chrome --use-angle=gl --in-process-gpu
```
In other words, it works around https://issues.chromium.org/issues/326752457 when Chrome is using ANGLE's desktop OpenGL back end as well as when Chrome is using ANGLE's OpenGL ES back end.  At least in my testing, the desktop OpenGL back end doesn't seem to suffer from the pipeline stalls described in https://issues.chromium.org/issues/326752458, but the WebGL frame rate is also reduced for unknown reasons.  (It seems to top out at 45-50 fps, even though the GPU is clearly in use.)

In my testing with TurboVNC, `--use-angle=gl` isn't necessary, as Chrome seems to pick the desktop OpenGL back end by default as long as `VGL_CHROMEHACK=1` is specified.  Your mileage may vary.

**Comment by dcommander** [comment]
Verified that the latest version available as of this writing (v138) behaves identically to v129.
