### ISSUE TITLE
What is the equivalent of VGL_DISPLAY for EGL?

### ISSUE THREAD

**Issue by muratmaga** [VirtualGL/virtualgl#268]
I have multiple GPUs in the system. We are using both the VGL and EGL backends. I would like both backends to use specifically the device `/dev/dri/card3`, which I can specify for VGL with VGL_DISPLAY environment variable. I couldn't locate the equivalent for egl.

vglrun -d egl defaults to a GPU that I need to reserve for machine learning.

**Comment by karlkleinpaste** [comment]
egl0, egl1, egl2, ...

**Comment by muratmaga** [comment]
I mean the environmental variable to set it for all users.

**Comment by dcommander** [comment]
It's the same. `VGL_DISPLAY=/dev/dri/card3` in your case.

**Comment by dcommander** [comment]
But note that you can't make "both back ends" do anything simultaneously. VGL can only use one back end or the other. The EGL/X11 API is always emulated using an EGL/DRI device. The GLX API is where the back end comes into play. The GLX back end modifies the GLX commands and passes them to the 3D X server. The typical way of using multiple GPUs with the GLX back end is to assign each to a different X screen and set `VGL_DISPLAY` to `:0.0`, `:0.1`, etc. to select a GPU. The EGL back end emulates GLX commands using an EGL/DRI device, so specifying that device in `VGL_DISPLAY` activates the EGL back end as well as selects the specified GPU.

**Comment by muratmaga** [comment]
Thanks for the clarification.

**Comment by dcommander** [comment]
But note that you can't make "both back ends" do anything simultaneously. VGL can only use one back end or the other. The GLX API is where the back end really comes into play. The GLX back end modifies the GLX commands and passes them to the 3D X server. The typical way of using multiple GPUs with the GLX back end is to assign each GPU to a different X screen and set `VGL_DISPLAY` to `:0.0`, `:0.1`, etc. to select a GPU. The EGL back end emulates GLX commands using an EGL/DRI device, so specifying that device in `VGL_DISPLAY` activates the EGL back end as well as selects the specified GPU. The EGL/X11 API piggybacks off of either the 3D X server or EGL/DRI device. So if the GLX back end is enabled, the EGL/X11 commands will be modified and sent to the specified 3D X server/screen. If the EGL back end is enabled, the EGL/X11 commands will be modified and sent to the specified EGL/DRI device.
