### ISSUE TITLE
Patches to build with --as-needed

### ISSUE THREAD

**Issue by scarabeusiv** [VirtualGL/virtualgl#28]
Hello, when building package for openSUSE I had to create two patches to build with --as-needed and -z,now:

This makes sure that libgl is correctly put even when build with the --as-needed
https://build.opensuse.org/package/view_file/X11:Bumblebee/VirtualGL/virtualgl-nodl.patch?expand=1

 This makes sure the package libs are properly linked and there are no undefined symbols during linking
https://build.opensuse.org/package/view_file/X11:Bumblebee/VirtualGL/VirtualGL-link-libs.patch?expand=1

**Comment by dcommander** [comment]
That doesn't make sense.  VirtualGL provides three separate interposer libraries.  They are not API libraries.  They are not designed to fully resolve until run time.  What you did above just broke VirtualGL.

**Comment by dcommander** [comment]
If you can provide more information as to why these patches would benefit the upstream VirtualGL code, then please supply it.  Otherwise, I am forced to conclude that these patches are a result of misunderstanding the fundamental purpose of VirtualGL.

**Comment by dcommander** [comment]
Closed due to lack of response.  It is my belief, based on reviewing your patches, that you broke critical VirtualGL functionality by including them, and your unwillingness to defend your position makes it impossible for me to conclude otherwise.
