### ISSUE TITLE
Regression on VGL_SAMPLES 

### ISSUE THREAD

**Issue by hernando** [VirtualGL/virtualgl#29]
VGL_SAMPLES has stopped working after commit 9fe3458951a076b3b269e88ad5ca67874bb10b75. 
When used, vglrun prints

```
Error: couldn't get an RGB, Double-buffered visual
```

and then exits.

I've tested in different graphics cards, but all are nVidia. The application I was using for testing was glxgears.

It seems that GLX_PIXMAP_BIT can't be used in combination with GLX_SAMPLES, at least where I tested, but it don't find anywhere that's truly the case.

**Comment by dcommander** [comment]
Weird.  OK, I'll see if I can reproduce it on one of my nVidia machines.
