### ISSUE TITLE
couldn't open display on debian 8

### ISSUE THREAD

**Issue by harveyslash** [VirtualGL/virtualgl#36]
I am trying to get opengl work for one of my projects. 
I have done 
/opt/VirtualGL/bin/vglserver_config 
then chose all recommended settings
```
Choose:
1

Restrict 3D X server access to vglusers group (recommended)?
[Y/n]
y

Restrict framebuffer device access to vglusers group (recommended)?
[Y/n]
y

Disable XTEST extension (recommended)?
[Y/n]
y
... Creating vglusers group ...
groupadd: group 'vglusers' already exists
Could not add vglusers group (probably because it already exists.)
... Granting read permission to /etc/opt/VirtualGL/ for vglusers group ...
... Creating /etc/modprobe.d/virtualgl.conf to set requested permissions for
    /dev/nvidia* ...
... Adding vglgenkey to /etc/kde4/kdm/Xsetup script ...
... Adding display-setup-script=vglgenkey to /etc/lightdm/lightdm.conf ...
... Disabling XTEST extension in /etc/kde4/kdm/kdmrc ...
```

Done. You must restart the display manager for the changes to take effect.
then i logged in using vglconnect -x user:pass as described. Then in that same ssh session , i did vglrun glxgears, and it just wont run . This is the output of vglrun +v glxgears :
[VGL] Shared memory segment ID for vglconfig: 360448
[VGL] VirtualGL v2.3.2 64-bit (Build 20121002)
[VGL] Opening local display :0
Error: couldn't open display 129.21.147.40:0

**Comment by dcommander** [comment]
It is not necessary to post your question in two places.  I will answer it in the first place it is posted.  Please refer to my answer on SourceForge.
