### ISSUE TITLE
VirtualGL on Arm issue

### ISSUE THREAD

**Issue by tekcomm** [VirtualGL/virtualgl#38]
I am successfully running virtual gl on linux under ubuntu 16.04 and using as the client a arm based geekbox running ubuntu 14.04. I compiled libjpeg, turbovnc and created debs. It was not a easy and not to hard of a task the main problem was libjpeg needed ./configure --with-java and the configure file path pointed to the includes for the java sdk installation. Turbovnc needed FindJNI.cmake modified so cmake would find the java sdk. I compiled it and it worked :). Then when I used it I got horrible frame rates 4-5 fps. While hunting down the java sdk I noticed a paper on speed times between oracle and the openjava. When I deleted everything and recompiled with oracle 8 se for armhf. I got 25+ fps. So Im posting here in case anyone has the same issue.

**Comment by dcommander** [comment]
Good to know. I can usually get around FindJNI problems by explicitly setting the following CMake variables:
‘‘‘
JAVA_AWT_INCLUDE_PATH
JAVA_AWT_LIBRARY
JAVA_INCLUDE_PATH
JAVA_INCLUDE_PATH2
JAVA_JVM_LIBRARY
```
`JAVA_AWT_INCLUDE_PATH` is the location of jawt.h, `JAVA_INCLUDE_PATH` is the location of jni.h, and `JAVA_INCLUDE_PATH2` is usually ${JAVA_INCLUDE_PATH}/linux.
