### ISSUE TITLE
PCSX2 not working

### ISSUE THREAD

**Issue by DocMAX** [VirtualGL/virtualgl#49]
Hello,
PCSX2 just crashes when using VirtualGL (arch linux both sides).
Can you confirm?
DocMAX

**Comment by dcommander** [comment]
Are you using the Arch distribution of VGL or one of our official binaries? There were problems in the past with the Arch distribution not being built correctly and thus causing problems with applications that dlopen() libGL. If you can reproduce the crash with our official binaries (NOTE: you can use rpmextract to install one of our RPM files under Arch), then I'll try to reproduce the problem on one of my machines.

**Comment by DocMAX** [comment]
Never mind, it works. I had misconfigured VGL. Thx.
