### ISSUE TITLE
nvenc

### ISSUE THREAD

**Issue by DocMAX** [VirtualGL/virtualgl#51]
Will you add nvenc (nvidia hardware encoding) as an option to encode and stream?

**Comment by dcommander** [comment]
See https://github.com/TurboVNC/turbovnc/issues/19.  It's a complicated issue, and I'm still researching it at the low level.  I'm not sure yet whether it makes more sense to add NVENC support to VirtualGL or to TurboVNC.  If added to TurboVNC, then it might be implemented "naively" (by using NVENC to encode the entire desktop as a video frame), or it might be implemented by handing off a PBO handle from VirtualGL to TurboVNC using an as-yet-to-be-developed X extension and then letting TurboVNC control the encoding.
