### ISSUE TITLE
ERROR: vglclient failed to execute.

### ISSUE THREAD

**Issue by martin-fzd** [VirtualGL/virtualgl#52]
Hi!
I installed virtualgl on cygwin under windows but I face this error:

> $ vglconnect -display 1 user@server-i ~/.ssh/mysshstuff
>VirtualGL Client 64-bit v2.5.2 (Build 20170302)
>[VGL] ERROR: vglclient failed to execute.

It works, however, well when I start virtualgl under a native ubuntu client.

What's the problem?

**Comment by dcommander** [comment]
A couple of obvious problems:
* You need a space between "user@server" and "-i"
* You need to specify "-display :1.0", not "-display 1" (assuming Cygwin/X is in fact running on display :1.0.  Generally it isn't necessary to specify "-display", since vglconnect will pick this up from the DISPLAY environment variable.

**Comment by martin-fzd** [comment]
Thanks for your quick response.
I see the same error when I configure the `-display` flag as shown, I'll get the same error as before.
When running without `-display` flat, I see this error: 
>vglconnect user@server -i ~/.ssh/mysshstuff
>[VGL] ERROR: An X display must be specified, either by using the -display
>[VGL]    argument to vglconnect or by setting the DISPLAY environment variable

**Comment by dcommander** [comment]
"vglclient failed to execute" means that vglclient can't communicate with Cygwin/X.  Make sure that Cygwin/X is actually running.  If it is, then make sure that the `-display` argument to vglconnect or the `DISPLAY` environment variable matches the display on which Cygwin/X is listening.  If you have any doubts about this, then launch xterm from the Cygwin/X taskbar menu and run vglconnect from within xterm.  That will ensure that the `DISPLAY` environment is set correctly.

**Comment by martin-fzd** [comment]
It works now.
Install Cygwin/X according to https://x.cygwin.com/docs/ug/setup.html
Launch XWinServer
Set the `DISPLAY` variable:
>export DISPLAY=:0.0
enjoy :)
