### ISSUE TITLE
display error in Siemens NX

### ISSUE THREAD

**Issue by sh3000** [VirtualGL/virtualgl#57]
when I using NX though Virtualgl，by doing section operation ，the option SHOW CAP and SHOW INTERFERENCE can not display correctly, it dispaly a huge plane, not a sectction plane. please help me to solve this issue, thanks

**Comment by dcommander** [comment]
@nathankidd, have you seen this with NX?  I do not have access to the application and thus have no way of testing or diagnosing this problem myself.

**Comment by nathankidd** [comment]
On 03/01/18 11:05 AM, DRC wrote:
> @nathankidd <https://github.com/nathankidd>, have you seen this with NX?
> I do not have access to the application and thus have no way of testing
> or diagnosing this problem myself.

Unfortunately, I don't have access to that application at this time.

**Comment by sh3000** [comment]
hi ， 
thank you for your reply.

i can send you a NX10,
https://pan.baidu.com/s/1qYDTslA, and
the crack file 
https://pan.baidu.com/s/1bpNNiqF

sh3000
发自我的 iPhone

**Comment by nathankidd** [comment]
@sh3000, as an FYI: from your signature I'd guess you're in China, where in my experience software licenses/copyright are often treated more, er, loosely.  You'll find that in many other countries, licenses/copyright are much more strictly adhered to, to the point that the suggestion above becomes border-line offensive, not least because of the potential legal suicide it could entail.  I suggest removing that comment.

**Comment by dcommander** [comment]
I removed the comment.  In addition to being in violation of the U.S. Digital Millennium Copyright Act,  the download required installing a download manager, which is a potential malware risk.

**Comment by sh3000** [comment]
sorry, i will not do that again, the download manager is baidu net disk, it’s very popular in china, it’s safe i think.


发自我的 iPhone

**Comment by nathankidd** [comment]
Another theoretical possibility would be to use [ApiTrace](https://apitrace.github.io/) to capture the same action when it works (without VirtualGL).  Then test replaying back that trace while using VirtualGL to see if it reproduces the problem.  (Note: I haven't tested this; it might not work if ApiTrace does tricks with the OpenGL API)

**Comment by sh3000** [comment]
OK，i will try the apitrace

发自我的 iPhone

**Comment by sh3000** [comment]
hi



I have installed the apitrace,and by using command "apitrace trace --api egl vglrun /usr/ugs100/bin/ugii", and got a trace file, you can check it in the attechment file .


songhui







At 2018-01-04 23:01:28, "Nathan Kidd" <notifications@github.com> wrote:


Another theoretical possibility would be to use ApiTrace to capture the same action when it works (without VirtualGL). Then test replaying back that trace while using VirtualGL to see if it reproduces the problem. (Note: I haven't tested this; it might not work if ApiTrace does tricks with the OpenGL API)

**Comment by sh3000** [comment]
i can’t send apitrace file by reply the mail which was sent by github,could you give me your email, thank you 

发自我的 iPhone

**Comment by nathankidd** [comment]
On 16/01/18 01:58 AM, sh3000 wrote:
> I have installed the apitrace,and by using command "apitrace trace --api
> egl vglrun /usr/ugs100/bin/ugii", and got a trace file, you can check it
> in the attechment file .

Suggestion: Play back the trace file under VirtualGL, and make sure you
can observe the wrong drawing behaviour.

**Comment by dcommander** [comment]
Yes.  If you can reproduce the issue using the apitrace, then you can e-mail it to me here:
https://virtualgl.org/About/Contact

**Comment by dcommander** [comment]
Your trace file was captured incorrectly.  Please re-capture it using

```
apitrace trace /usr/ugs100/bin/ugii
```

* Do not pass `--api` to apitrace.
* Do not use vglrun with apitrace.

**Comment by dcommander** [comment]
Also, you can play back the trace using either

```
glretrace {trace_file}
```
or
```
apitrace replay {trace_file}
```

If it doesn't play back properly, then it wasn't captured properly.

**Comment by sh3000** [comment]
OK， I will try it late

thank you

发自我的 iPhone

**Comment by dcommander** [comment]
@sh3000 Have you tried to capture the libGL API trace and play it back, as I suggested above?  Otherwise, there is little I can do to assist you in solving this problem.

**Comment by dcommander** [comment]
Closing due to lack of response from the user.  I cannot solve problems when people cannot be bothered to provide me with the requested information on the problems.
