### ISSUE TITLE
vgl_xauth_key does not exist

### ISSUE THREAD

**Issue by jacknlliu** [VirtualGL/virtualgl#61]
```sh
$ sudo  /opt/VirtualGL/bin/vglgenkey

xauth:  file /etc/opt/VirtualGL/vgl_xauth_key does not exist
```

System Information
```
Ubuntu 16.04  with gnome3
VirtualGL: 2.5.2
```

**Comment by dcommander** [comment]
vglgenkey is not meant to be run by itself.  vglserver_config modifies the display manager startup script to run vglgenkey whenever the DM launches.  Refer to the User's Guide.
