### ISSUE TITLE
glxpheres64 not found

### ISSUE THREAD

**Issue by eas-msky** [VirtualGL/virtualgl#64]
Hello.
My system is Kali linux. i'am installed bumblebee and virtualgl_2.5.2_amd64.deb
next problem:
`root@kali:~# optirun glxpheres64`
`/usr/bin/vglrun: 257: exec: glxpheres64: not found
`
help please!

**Comment by dcommander** [comment]
It's under /opt/VirtualGL/bin.

**Comment by dcommander** [comment]
... assuming you are using our official DEB package ...
