### ISSUE TITLE
vgl_xauth_key gets stomped in lightdm/XDMCP config

### ISSUE THREAD

**Issue by srd424** [VirtualGL/virtualgl#70]
I have a "compute" server set-up to serve X sessions via XDMCP. It currently uses lightdm, which invokes vglgenkey twice, the second time deleting the key and then failing (causing sessions to fail to start)

```
[+0.23s] DEBUG: Launching process 18614: /opt/VirtualGL/bin/vglgenkey
[+0.23s] DEBUG: Process 18614 exited with return value 0
[+0.23s] DEBUG: Seat seat0: Exit status of /opt/VirtualGL/bin/vglgenkey: 0
[+0.24s] DEBUG: Seat seat0: Display server ready, starting session authentication
[..]
[+14.83s] DEBUG: Got ForwardQuery(client_address=C0A880A3 client_port=C81F authentication_names=[]) from 192.168.128.163:177
[..]
[+15.37s] DEBUG: Seat (null): Creating display server of type x
[+15.37s] DEBUG: DisplayServer x-192.168.128.163-0: Connecting to XServer 192.168.128.163:0
[+15.38s] DEBUG: Launching process 18699: /opt/VirtualGL/bin/vglgenkey
[+15.39s] DEBUG: Process 18699 exited with return value 1
[+15.39s] DEBUG: Seat (null): Exit status of /opt/VirtualGL/bin/vglgenkey: 1
[+15.39s] DEBUG: Seat (null): Stopping display server due to failed setup script
[+15.39s] DEBUG: Seat (null): Display server stopped
```

The following quick hack has sorted things out here, not sure if it is the Right Thing though.

```
--- vglgenkey.orig	2018-06-14 11:54:34.066727337 +0100
+++ vglgenkey	2018-06-14 06:26:26.375493554 +0100
@@ -1,5 +1,8 @@
 #!/bin/sh
 XAUTH=xauth
+if ! echo $DISPLAY | grep -q '^:'; then
+	exit 0
+fi
 if [ -x /usr/X11R6/bin/xauth ]; then
 	XAUTH=/usr/X11R6/bin/xauth
 fi
```

**Comment by dcommander** [comment]
XDMCP is an ancient, insecure, and poorly-supported mechanism, and I'm surprised you can make it work at all.  I'm sure it required enabling TCP connections to your 3D X server, which is generally a bad idea.  There are better ways of accomplishing the same thing, such as using TurboVNC with Unix Login authentication.

That being said, I think the better solution is to modify vglgenkey such that it attempts to create the new key under a different filename and doesn't delete the old key unless the new key is created successfully.  Try the following patch and see if it works for you:

```
--- a/server/vglgenkey
+++ b/server/vglgenkey
@@ -9,9 +9,16 @@ fi
 if [ ! -d /etc/opt/VirtualGL ]; then
   mkdir -p /etc/opt/VirtualGL
 fi
-if [ -f /etc/opt/VirtualGL/vgl_xauth_key ]; then
-  rm /etc/opt/VirtualGL/vgl_xauth_key
+$XAUTH -f /etc/opt/VirtualGL/vgl_xauth_key.new generate $DISPLAY . trusted timeout 0 ||
+  $XAUTH -f /etc/opt/VirtualGL/vgl_xauth_key.new add $DISPLAY . `$XAUTH list | awk '{print $3}' | uniq`
+if [ $? -eq 0 ]; then
+  if [ -f /etc/opt/VirtualGL/vgl_xauth_key ]; then
+    rm /etc/opt/VirtualGL/vgl_xauth_key
+  fi
+  mv /etc/opt/VirtualGL/vgl_xauth_key.new /etc/opt/VirtualGL/vgl_xauth_key
+else
+  if [ -f /etc/opt/VirtualGL/vgl_xauth_key.new ]; then
+    rm /etc/opt/VirtualGL/vgl_xauth_key.new
+  fi
 fi
-$XAUTH -f /etc/opt/VirtualGL/vgl_xauth_key generate $DISPLAY . trusted timeout 0 ||
-  $XAUTH -f /etc/opt/VirtualGL/vgl_xauth_key add $DISPLAY . `$XAUTH list | awk '{print $3}' | uniq`
 chmod 644 /etc/opt/VirtualGL/vgl_xauth_key
```

**Comment by dcommander** [comment]
@srd424 please test the patch as requested.

**Comment by srd424** [comment]
Well, I'm ancient and unsupported as well, old enough that XDMCP was the direction I instinctively went in when I wanted to set-up remote login quickly & easily (and it was, surprisingly.) This is a switched local LAN so probably safe.

The patch works but looking into it more closely it seems lightdm is erroneously failing to set DISPLAY which is why vglgenkey is in turn failing. If the lightdm bug is ever fixed we will end up being called for every remote display and presumably overwriting vgl_xauth_key with cookies for the remote servers which are no use to us? So perhaps a combination of the patches is best.

The "Right Thing" is probably to make the lightdm.conf changes apply only to local servers, but it's not immediately obvious how to do that..

**Comment by dcommander** [comment]
It seems to work fine for me as well (tested on various Ubuntu releases and Fedora), but where are you seeing that the seat name is null for non-local logins?

**Comment by srd424** [comment]
Hmm, https://www.freedesktop.org/wiki/Software/systemd/multiseat/ sort of says it:
> A session is bound to one or no seats (the latter for 'virtual' ssh logins)

Also just found this lightdm commit:
https://github.com/CanonicalLtd/lightdm/commit/5847d300fda3a5a7d5dabecb8dcb2af9b354f0c3
Which should change the XDMCP seat name (within lightdm, at least) to "xdmcp..." so we should still be good?

**Comment by dcommander** [comment]
You said "Ah, looking at systemd/logind docs, seat name is always null for non-local logins".  Where does it say that?

**Comment by srd424** [comment]
Obviously I mis-remembered slightly. But lightdm takes the seat name from logind if a seat is a created, and from the doc above it is clear remote logins do not count as seats. In actual use lightdm does not create new seats for XDMCP sessions, and I can't find any code to do this - looking at the login manager API, the only way to create a new seat is by attaching a device from /sys to an unused seat ID, which obviously can't be done for an XDMCP session. lightdm seems to just use NULL (before above commit) or "xdmcp" as a virtual seat name internally, so as long as everything honours
> Seats are identified by seat names, which are short strings (<= 64chars), that start with the four characters "seat"

I don't see why the Seat:seat* approach shouldn't be robust.
