### ISSUE TITLE
env var to force log flushes?

### ISSUE THREAD

**Issue by smarguet** [VirtualGL/virtualgl#72]
When debugging applications which segfault or get a kill signal, the VGL_LOG may not be written. It could be helpful to have an environment variable to enable flush on frame draws or other events.

**Comment by dcommander** [comment]
I'll look into it.

**Comment by dcommander** [comment]
I looked into this, and VirtualGL already flushes the log frequently when tracing mode is active (`export VGL_TRACE=1` or pass `+tr` to vglrun.)  If tracing mode is inactive, then the log won't really contain anything that would help you debug a segfault.  However, you can set `VGL_DEBUG=1` or pass `+de` to vglrun to cause VirtualGL to pause when the first interposed function is called, thus allowing you to attach a debugger to the 3D application process.

One thing to be mindful of is the fact that, if you are writing the log to a remote directory (such as an NFS-mounted home directory), then it may not be flushed until the program exits.  That behavior is a product of NFS, not VirtualGL.
