### ISSUE TITLE
Support for recent chrome/chromium ?

### ISSUE THREAD

**Issue by smarguet** [VirtualGL/virtualgl#73]
Google Chrome version 54 or prior works perfect with virtualgl.  55+ returns:

$ vglrun +v /opt/google/chrome-beta/chrome --disable-gpu-sandbox 
```
[VGL] Shared memory segment ID for vglconfig: 341377093
[VGL] VirtualGL v2.5.2 64-bit (Build 20180619)
[VGL] Shared memory segment ID for vglconfig: 341508169
[VGL] VirtualGL v2.5.2 64-bit (Build 20180619)
[VGL] NOTICE: Replacing dlopen("libGL.so.1") with dlopen("libvglfaker.so")
[VGL] Opening connection to 3D X server :0
[265420:265420:0626/162302.840890:ERROR:gl_surface_glx.cc(126)] Failed to get GLXConfig
[265420:265420:0626/162302.841198:ERROR:gl_surface_glx.cc(448)] CreateDummyWindow(gfx::GetXDisplay()) failed
[265420:265420:0626/162302.841219:ERROR:gl_initializer_x11.cc(157)] GLSurfaceGLX::InitializeOneOff failed.
[265420:265420:0626/162302.844260:ERROR:viz_main_impl.cc(201)] Exiting GPU process due to errors during initialization
[265375:265393:0626/162302.845793:ERROR:service_manager_context.cc(250)] Attempting to run unsupported native service: /opt/google/chrome-beta/content_gpu.service
[VGL] Shared memory segment ID for vglconfig: 341573705
[VGL] VirtualGL v2.5.2 64-bit (Build 20180619)
[265375:265375:0626/162302.987855:ERROR:gpu_process_transport_factory.cc(1016)] Lost UI shared context.
[1:9:0626/162303.000131:ERROR:command_buffer_proxy_impl.cc(132)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.

```

Firefox & derivatives' WebGL works, but unfortunately they have other issues with some Jupyter kernels. Also, Electron/node & other apps bundle/require Chromium and WebGL dependent windows therein only show "Webgl is not supported by your browser ..." Any tips are much appreciated.

We are on SuSE Enterprise 12 SP3 kernel 4.4.132-94.33-default #1 SMP Tue May 29 20:09:56 UTC 2018 (76aae3b) x86_64 GNU/Linux and VirtualGL is bundled with Nomachine NX 6.2.4_1.

**Comment by dcommander** [comment]
I'll look into it.

**Comment by dcommander** [comment]
I tried Chromium 68.0.3440.75 from SUSE Package Hub, running under SLES 12 SP3, and it works with VGL (either 2.5.2 or 2.6 beta) regardless of whether `--disable-gpu-sandbox` is specified.  I also tried the official Google package (68.0.3440.106.)  I had to install the official package with `rpm --no-deps`, but it also works fine.

Please provide the following information:
* The output of `/opt/VirtualGL/bin/glxinfo -display :0 -c`
* The location of the specific Chrome binary you are testing
* The GPU make, model, and driver you are using

**Comment by dcommander** [comment]
@smarguet can you provide the requested information?  I'd like to make sure that this isn't a VirtualGL bug before releasing 2.6.

**Comment by dcommander** [comment]
The only nVidia machines I have are running RHEL and Fedora.  I'll test 68.x on Fedora to see if I can reproduce the problem there.

**Comment by dcommander** [comment]
I was able to reproduce the problem with the nVidia drivers.  Investigating.

**Comment by dcommander** [comment]
For me, setting `VGL_DEFAULTFBCONFIG=GLX_ALPHA_SIZE,8` in the environment worked around the problem.  Can you confirm?

**Comment by dcommander** [comment]
For now, I'm documenting the workaround I discovered.  I've started a discussion on the virtualgl-devel mailing list regarding ways of improving VirtualGL's visual matching system so as to avoid issues like this in the future.
