### ISSUE TITLE
Patreon or any other platform - Monthly donation

### ISSUE THREAD

**Issue by JeffLabonte** [VirtualGL/virtualgl#75]
Hi!

I would like to make donations monthly through something like patreon or any other platform. 

If I am correct bumblebee, uses your code so we, nvidia user, can use our GPU as we please, so it might be a good plan to contact these guys as well!

**Comment by dcommander** [comment]
Much appreciated! There is a Donate button on our [web site](https://VirtualGL.org) that lets you set up a recurring monthly donation using either a credit card or PayPal account.
