### ISSUE TITLE
Vglrun on RHEL7

### ISSUE THREAD

**Issue by badrharbi** [VirtualGL/virtualgl#78]
We have noticed that glXCreateContext 5 seconds on RHEL 7 and RHEL6 takes 12 ms and we are looking for a way to address this performance issue.
 
We are using VirtualGL 2.4
 
Redhat 7
 
vglrun glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: Tesla K80/PCIe/SSE2
OpenGL core profile version string: 4.4.0 NVIDIA 390.46
OpenGL core profile shading language version string: 4.40 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 390.46
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
 
->vglrun –v +tr myapp
 
[VGL] XOpenDisplay (name=NULL
[VGL]   XQueryExtension (dpy=0x00e01ad0(:0) name=XKEYBOARD *major_opcode=135 *first_event=85 *first_error=137 ) 0.012159 ms
[VGL]
[VGL]   XQueryExtension (dpy=0x00e1ebd0(10.3.112.159:0) name=XKEYBOARD *major_opcode=139 *first_event=85 *first_error=139 ) 0.744104 ms
[VGL] dpy=0x00e1ebd0(10.3.112.159:0) ) 13.697863 ms
[VGL] glXChooseVisual (dpy=0x00e1ebd0(10.3.112.159:0) screen=0 attrib_list=[0x0004 0x0008=0x0008 0x0009=0x0008 0x000a=0x0008 0x000c=0x0001 0x0005 ] [VGL] dlopen (filename=libGLX_nvidia.so.0 flag=1[VGL] dlopen (filename=libc.so.6 flag=1 retval=0x2ac799762990)
[VGL] dlopen (filename=NULL flag=1 retval=0x2ac799942150)
[VGL] dlopen (filename=NULL flag=1 retval=0x2ac799942150)
[VGL] dlopen (filename=libpthread.so.0 flag=257 retval=0x2ac799765500)
[VGL] dlopen (filename=NULL flag=1 retval=0x2ac799942150)
[VGL] dlopen (filename=NULL flag=1 retval=0x2ac799942150)
[VGL] dlopen (filename=/lib64/libc.so.6 flag=1 retval=0x2ac799762990)
[VGL] dlopen (filename=/lib64/libdl.so.2 flag=1 retval=0x2ac7997409e0)
[VGL] dlopen (filename=/lib64/libpthread.so.0 flag=1 retval=0x2ac799765500)
[VGL] dlopen (filename=libnvidia-tls.so.390.46 flag=1 retval=0x00e2a5b0)
[VGL] dlopen (filename=NULL flag=1 retval=0x2ac799942150)
[VGL] dlopen (filename=libc.so.6 flag=1 retval=0x2ac799762990)
retval=0x00e2a0c0)
[VGL] dlopen (filename=NULL flag=1 retval=0x2ac799942150)
[VGL] dlopen (filename=NULL flag=1 retval=0x2ac799942150)
vis=0x00eb46a0(0x21) config=0x00e7b5e0(0x10d) ) 16.679049 ms
Visual ID of window: 0x21
[VGL] XCreateWindow (dpy=0x00e1ebd0(10.3.112.159:0) parent=0x00000051 x=0 y=0 width=1240 height=900 depth=24 c_class=1 visual=0x00e29580(0x21) win=0x01a00002 ) 0.001907 ms
[VGL] glXCreateContext (dpy=0x00e1ebd0(10.3.112.159:0) vis=0x00eb46a0(0x21) share_list=0x00000000 direct=1 config=0x00e7b5e0(0x10d) ctx=0x00f5f798 ) 5699.894905 ms
[VGL] glXIsDirect (dpy=0x00e1ebd0(10.3.112.159:0) ctx=0x00f5f798 direct=1 ) 0.000000 ms
Context is Direct
[VGL] glXMakeCurrent (dpy=0x00e1ebd0(10.3.112.159:0) drawable=0x01a00002 ctx=0x00f5f798
[VGL]   XQueryExtension (dpy=0x00e1ebd0(10.3.112.159:0) name=XVideo *major_opcode=0 *first_event=0 *first_error=0 ) 0.602007 ms
[VGL]
 
 
 
 
 
Redhat 6
 
vglrun glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: Tesla K80/PCIe/SSE2
OpenGL version string: 4.5.0 NVIDIA 346.73
OpenGL shading language version string: 4.50 NVIDIA
OpenGL extensions:
 
 
->vglrun –v +tr myapp
[VGL] dlopen (filename=libc.so.6 flag=1 retval=0x2b48a2e14320)
[VGL] dlopen (filename=NULL flag=1 retval=0x316aa21188)
[VGL] dlopen (filename=NULL flag=1 retval=0x316aa21188)
[VGL] dlopen (filename=libpthread.so.0 flag=257 retval=0x2b48a2e14ce8)
[VGL] dlopen (filename=NULL flag=1 retval=0x316aa21188)
[VGL] dlopen (filename=NULL flag=1 retval=0x316aa21188)
[VGL] dlopen (filename=/lib64/libc.so.6 flag=1 retval=0x2b48a2e14320)
[VGL] dlopen (filename=/lib64/libdl.so.2 flag=1 retval=0x2b48a2b15000)
[VGL] dlopen (filename=/lib64/libpthread.so.0 flag=1 retval=0x2b48a2e14ce8)
[VGL] dlopen (filename=libnvidia-tls.so.346.73 flag=1 retval=0x2b48a354a558)
[VGL] dlopen (filename=NULL flag=1 retval=0x316aa21188)
[VGL] dlopen (filename=libc.so.6 flag=1 retval=0x2b48a2e14320)
[VGL] XOpenDisplay (name=NULL
[VGL]   XQueryExtension (dpy=0x02326300(10.3.112.159:0) name=XKEYBOARD *major_opcode=139 *first_event=85 *first_error=139 ) 0.859022 ms
[VGL] dpy=0x02326300(10.3.112.159:0) ) 13.998032 ms
[VGL] glXChooseVisual (dpy=0x02326300(10.3.112.159:0) screen=0 attrib_list=[0x0004 0x0008=0x0001 0x0009=0x0001 0x000a=0x0001 0x0005 0x000c=0x0001 ] [VGL] dlopen (filename=NULL flag=1 retval=0x316aa21188)
[VGL] dlopen (filename=NULL flag=1 retval=0x316aa21188)
v=0x02331c40(0x21) c=0x0000010d(0x10d) ) 13.089895 ms
[VGL] XCreateWindow (dpy=0x02326300(10.3.112.159:0) parent=0x00000051 x=0 y=0 width=300 height=300 depth=24 c_class=1 visual=0x02330cc0(0x21) win=0x01a00002 ) 0.002146 ms
[VGL] glXCreateContext (dpy=0x02326300(10.3.112.159:0) vis=0x02331c40(0x21) share_list=0x00000000 direct=1 c=0x0000010d(0x10d) ctx=0x0233b870 ) 12.169123 ms
[VGL] glXMakeCurrent (dpy=0x02326300(10.3.112.159:0) drawable=0x01a00002 ctx=0x0233b870
[VGL]   XQueryExtension (dpy=0x02326300(10.3.112.159:0) name=XVideo *major_opcode=0 *first_event=0 *first_error=0 ) 0.854015 ms
[VGL]

**Comment by dcommander** [comment]
It appears from your X display string that you are using X11 over TCP, which is not a common configuration.  Usually the non-OpenGL-related X11 traffic is either tunneled through SSH (that is the default when using vglconnect) or handled by an X proxy (i.e. rendered on the server, with only images being sent to the client.)  You might try setting `VGL_PROBEGLX=0` in the environment on the server prior to invoking vglrun.  That will prevent any GLX commands from being sent over the network (those commands are sent to the 2D X server in order to figure out whether it supports quad-buffered stereo visuals.)  However, the slow-down may simply be due to a slow network connection, in which case your only remedy will be to use an X proxy such as TurboVNC.  The VirtualGL Transport (vglconnect) is not meant for high-latency/low-bandwidth networks.

If the problem is still reproducible in an X proxy environment, then I have no clue what's causing it.
