### ISSUE TITLE
headless machine with matrox card?

### ISSUE THREAD

**Issue by thomasbeaudry** [VirtualGL/virtualgl#80]
Hi,
I am trying to get virtualGL to work on a headless server that has a matrox card.  Here is my bus info:

0a:00.0 VGA compatible controller: Matrox Electronics Systems Ltd. G200eR2 (rev 01)

I was trying to follow the instructions here: https://virtualgl.org/Documentation/HeadlessNV  but i'm not sure that they apply.

Thanks!

**Comment by dcommander** [comment]
Those instructions rely on nVidia-specific functionality, so they most likely don't apply.  Are you sure that headless operation is even possible with a Matrox card?

**Comment by dcommander** [comment]
You need to post to the virtualgl-users Google group, then. I’m the only one who monitors GitHub issues.
