### ISSUE TITLE
VirtualGL in a TurboVNC viewer

### ISSUE THREAD

**Issue by toonday** [VirtualGL/virtualgl#82]
I installed VirtualGL on linux box in the cloud.
I have a TurboVNC viewer for accessing the linux box.
The following command works for me `$ glxgears`
but using vglrun is giving me lots of issues:

COMMAND 1
`$ sudo vglrun +v -d :1 glxgears`
`[VGL] Shared memory segment ID for vglconfig: 3506201
[VGL] VirtualGL v2.6 64-bit (Build 20180824)
[VGL] Opening connection to 3D X server :1
[VGL] WARNING: VirtualGL attempted and failed to obtain a true color visual on
[VGL]    the 3D X server :1 suitable for off-screen rendering.
[VGL]    This is normal if the 3D application is probing for visuals with
[VGL]    certain capabilities, but if the app fails to start, then make sure
[VGL]    that the 3D X server is configured for true color and has accelerated
[VGL]    3D drivers installed.
Error: couldn't get an RGB, Double-buffered visual`

COMMAND 2
`$sudo vglrun +v -d :1 /opt/VirtualGL/bin/glxspheres64`
`Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
[VGL] Shared memory segment ID for vglconfig: 4128779
[VGL] VirtualGL v2.6 64-bit (Build 20180824)
[VGL] Opening connection to 3D X server :1
ERROR in line 643:
Could not obtain RGB visual with requested properties`

[glxinfo_debug.txt](https://github.com/VirtualGL/virtualgl/files/2386167/glxinfo_debug.txt)

**Comment by dcommander** [comment]
Why are you passing `-d :1`? The User’s Guide did not instruct you to do that, and that would only be appropriate if :1 is the 3D X server (the X server with the GPU attached.) Usually the GPU is attached to :0, which is the default value of `VGL_DISPLAY` (`vglrun -d`.)
