### ISSUE TITLE
Maybe bug, missing 'oldctx' NULL check

### ISSUE THREAD

**Issue by peterNordin** [VirtualGL/virtualgl#83]
I believe that I may have found a bug.

**Background:**
I am trying to run an opengl application with VirtualGL 2.6
Essentially I run:

mydesktop --vnc--> server (vglrun -c proxy -- ./myApplication)

This has worked fine for previous versions of VirtualGL up to version 2.5.2.

**Problem:**
With 2.6, myApplication aborts on startup and I see errors from VGL telling me of an "Invalid argument" inside findConfig.

I looked over the commit history since v2.5.2 and found the commit causing my problem, d771339c6e4fa6302ea2a2c8a7af000ce033a38a, where the following code was added:

In server/TempContext.h:

```
if(ctxhash.findConfig(oldctx))
    ctxChanged = true;
```

In all other places where findConfig is called, the argument 'ctx' (in this case 'oldctx') is checked for NULL before. In this case it is not.

Perhaps myApplication is slightly broken in some way, but 'oldctx' is NULL at least one time, so the application is aborted inside findConfig. (I did not check if it is reoccurring.)  

**Possible fix:**
I tried to fix this myself by adding a NULL check similar to the other places in the VirtualGL code.

`"if(oldctx && ctxhash.findConfig(oldctx))"`

I recompiled VirtualGL 2.6 with this change, and now myApplication starts as expected and it seem to work as usual. But I am not sure if the `ctxChanged` variable should be set to `true` or `false` when `oldctx` is NULL

**Comment by dcommander** [comment]
Derp.  Yes, my own unit test (fakerut) also exposes this problem.  Stand by.

**Comment by dcommander** [comment]
Fixed.  Pre-release build will be available shortly at this URL: https://virtualgl.org/DeveloperInfo/PreReleases (once completed, it will have today's date and a version number of 2.6.1.)
