### ISSUE TITLE
glxgears wont run

### ISSUE THREAD

**Issue by mathew2214** [VirtualGL/virtualgl#85]
when i connect to my host using vglconnect and try to run "vglrun +v glxgears" it does not start glxgears and instead outputs this to the terminal: https://pastebin.com/mAMCZ7XK

**Comment by mathew2214** [comment]
here is the output of those commands(when logged into a local x-terminal at the host): 
glreadtest with no arguments: https://pastebin.com/CgLstCXK
glreadtest -pbo : https://pastebin.com/BpC8Aset (it is exactly the same as with no arguments)
glreadtest -pm : https://pastebin.com/Jn93p2gS

since both glreadtest and glreadtest -pbo failed but glreadtest -pm did not, i tried running virtualGl with VGL_DRAWABLE=pixmap.  this allowed glxgears to run with vglrun when logged in to a local x terminal form the host. i then went to another machine and tried to use virtualGL remotely with vglconnect. 
the results of the glreadtest commands are the same as when ran form the host machine directly. but glxgears still will not run remotely. 
here is the output of "VGL_DRAWBLE=pixmap vglrun glxgears" when ran from a remote client connected with vglconnect: https://pastebin.com/Gkpu7mFT


the hosts graphics card is an AMD radeon R9 270x. AMD's official driver, AMDGPU, is not compatible with this card. the only AMD official driver that supports this card is FGLRX. FGLRX cannot be used in my configuration because FGLRX is incompatible with the current version of X11. i am using the open-source driver called "radeon" in this configuration as AMD does not make any usable drivers for this card.

**Comment by dcommander** [comment]
Yes, I am all too familiar with the fglrx compatibility issue, as I experience that problem with my own AMD GPUs.  That's one reason why about 99% of professional VirtualGL users are using nVidia GPUs.  I want VirtualGL to be vendor-neutral, but unfortunately AMD's drivers don't make that very easy sometimes.

As to why `VGL_DRAWABLE=pixmap` didn't work, it's because you misspelled `VGL_DRAWABLE`.

**Comment by dcommander** [comment]
For completeness, in case someone stumbles upon this with Google ...

Other users have discovered that setting `VGL_FORCEALPHA=1` is an effective workaround for the AMDGPU X_GLXCreatePbuffer issue.
