### ISSUE TITLE
support for nxproxy

### ISSUE THREAD

**Issue by hackoon** [VirtualGL/virtualgl#86]
I tried to integrate nxproxy with vglconnect but failed. Some "vglrun 'apps'" crash other open an empty frame (lutris). Any idea how to proceed? I know Nx does integrate virtualgl but I like to use it with the gpl nxproxy than comes with most distributions.

**Comment by dcommander** [comment]
Don't use vglconnect with nxproxy.  Just use vglrun, and it should work.
