### ISSUE TITLE
vglrun doesn't wrok in VNC session (Tumbleweed)

### ISSUE THREAD

**Issue by wddufo** [VirtualGL/virtualgl#99]
Hi,

I am reporting one issue when I use virtualgl with VNC. If my local user is logged in, I can successfully run `vglrun glxgears` on my VNC session. However, if the local user is logged out, `vglrun glxgears` will produce error message like this:

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  25
  Current serial number in output stream:  26
```

P.S. If I 'su' first in my VNC session,  `vglrun glxgears` works well regardless of the local login status.

My xorg.conf (my user has been added to the vglusers group):

```
# nvidia-xconfig: X configuration file generated by nvidia-xconfig
# nvidia-xconfig:  version 418.56
Section "DRI"
        Mode 0660
        Group "vglusers"
EndSection


Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0"
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
EndSection

Section "Files"
EndSection

Section "InputDevice"

    # generated from data in "/etc/sysconfig/mouse"
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "IMPS/2"
    Option         "Device" "/dev/input/mice"
    Option         "Emulate3Buttons" "yes"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"

    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "Unknown"
    HorizSync       28.0 - 33.0
    VertRefresh     43.0 - 72.0
    Option         "DPMS"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "Quadro RTX 5000"
    BusID          "PCI:179:0:0"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "AllowEmptyInitialConfiguration" "True"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection
```
(system info: openSUSE Tumbleweed, nvidia 418.56, VirtualGL v2.5.2 64-bit (Build 20180619),TigerVNC 1.9.0)

Thank you in advance for any suggestions.

**Comment by dcommander** [comment]
Did you run `vglserver_config`, as instructed in the VirtualGL User's Guide?  That is necessary in order to grant access to the 3D X server when no local users are logged in.

**Comment by wddufo** [comment]
> Did you run `vglserver_config`, as instructed in the VirtualGL User's Guide? That is necessary in order to grant access to the 3D X server when no local users are logged in.

Thanks for your prompt reply. Yes, I did it before. I have also restarted my computer several times. 
```
Restrict 3D X server access to vglusers group (recommended)?
[Y/n]
 

Restrict framebuffer device access to vglusers group (recommended)?
[Y/n]


Disable XTEST extension (recommended)?
[Y/n]

... Creating vglusers group ...
groupadd: group 'vglusers' already exists
Could not add vglusers group (probably because it already exists.)
... Granting read permission to /var/lib/VirtualGL/ for vglusers group ...
... Creating /etc/modprobe.d/virtualgl.conf to set requested permissions for
    /dev/nvidia* ...
... Attempting to remove nvidia module from memory so device permissions
    will be reloaded ...
rmmod: ERROR: Module nvidia is in use by: nvidia_uvm nvidia_modeset
... Granting write permission to /dev/nvidia0 /dev/nvidiactl /dev/nvidia-modeset /dev/nvidia-uvm for vglusers group ...
... Granting write permission to /dev/dri/card0 for vglusers group ...
... Modifying /etc/X11/xorg.conf.d/99-virtualgl-dri to enable DRI permissions
    for vglusers group ...
... Modifying /etc/X11/xorg.conf to enable DRI permissions
    for vglusers group ...
... Adding vglgenkey to /etc/X11/xdm/Xsetup script ...
... Adding vglgenkey to /usr/share/sddm/scripts/Xsetup script ...
... Adding display-setup-script=vglgenkey to /etc/lightdm/lightdm.conf ...
... Disabling XTEST extension in /etc/X11/xdm/Xservers ...

Done. You must restart the display manager for the changes to take effect.

IMPORTANT NOTE: Your system uses modprobe.d to set device permissions. You
must execute rmmod nvidia with the display manager stopped in order for the
new device permission settings to become effective.
```

**Comment by dcommander** [comment]
A point of clarification:

When you say "if the local user is logged out," do you mean:
1. `vglrun glxgears` works fine while the user is logged in, but it throws an X11 error when they log out?  If so, this is expected behavior.  You generally can't log in or out locally on the 3D X server while VirtualGL is running, because logging out of the 3D X server typically causes it to reset, which dumps any connections that VirtualGL made to it.
2. `vglrun glxgears` won't work at all unless someone is logged in?  If that's the case, then it's probably because VirtualGL has never been tested on openSUSE Tumbleweed, so `vglserver_config` may not be properly configuring the display manager on that platform.

If openSUSE Tumbleweed uses GDM and supports Wayland, then that may be the problem as well.  If so, then you probably need to use the 2.6.x stable pre-release of VirtualGL (https://virtualgl.org/DeveloperInfo/PreReleases) in order to make `vglserver_config` work properly on that platform.  With Wayland-enabled versions of GDM, it is necessary to disable Wayland, which `vglserver_config` in the pre-release build now does.  Otherwise, GDM will use a Wayland server and not an X.org server to display the login prompt, so there is no 3D X server for VirtualGL to connect to.  Unfortunately, disabling Wayland in GDM also disables any ability to log in locally with a Wayland session, but logging in locally to the 3D X server is problematic for other reasons (including the X server reset issue described above.)  Generally the only supported way to log in locally on a VirtualGL server is to use multiple GPUs, dedicate one of them to VirtualGL, and run a headless X server on it.  Once the EGL back end is completed for VirtualGL 3.0, that will also allow you to use VirtualGL without a 3D X server, which will eliminate these limitations.

**Comment by wddufo** [comment]
> A point of clarification:
> 
> When you say "if the local user is logged out," do you mean:
> 
> 1. `vglrun glxgears` works fine while the user is logged in, but it throws an X11 error when they log out?  If so, this is expected behavior.  You generally can't log in or out locally on the 3D X server while VirtualGL is running, because logging out of the 3D X server typically causes it to reset, which dumps any connections that VirtualGL made to it.
> 2. `vglrun glxgears` won't work at all unless someone is logged in?  If that's the case, then it's probably because VirtualGL has never been tested on openSUSE Tumbleweed, so `vglserver_config` may not be properly configuring the display manager on that platform.

Sorry being unclear. "Local user is logged in" means the user is logged in using a screen physically connected to the machine. If this user keeps this session logged in, he/she can use `vglrun glxgears` perfectly fine in the VNC session. However, once the "local session" i.e. the session logged in using a screen physically connected to the machine is shut down, the `vglrun glxgears` will be terminated and show the error message pasted below
```
6669 frames in 5.0 seconds = 1333.662 FPS
7173 frames in 5.0 seconds = 1433.549 FPS
7141 frames in 5.0 seconds = 1428.027 FPS
4545 frames in 5.0 seconds = 906.854 FPS
6149 frames in 5.0 seconds = 1229.734 FPS
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 142447 requests (142447 known processed) with 0 events remaining.
```
Regarding the display manager in openSUSE Tumbleweed, it uses Simple Desktop Display Manager SDDM. 
```
~> systemctl status display-manager
  display-manager.service - X Display Manager
   Loaded: loaded (/usr/lib/systemd/system/display-manager.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-04-01 08:15:57 CEST; 24h ago
  Process: 2613 ExecStart=/usr/lib/X11/display-manager start (code=exited, status=0/SUCCESS)
 Main PID: 2639 (sddm)
    Tasks: 4 (limit: 5529)
   Memory: 127.0M
   CGroup: /system.slice/display-manager.service
                 2639 /usr/bin/sddm
                 5301 /usr/bin/X -nolisten tcp -auth /run/sddm/{644e35e7-f24e-4881-8680-0ebecc629daf} -background none -noreset -displayfd 18 -seat seat0 vt7
```
I am not familiar with Wayland. Google tells me that https://wiki.archlinux.org/index.php/SDDM

> Note: The Wayland windowing system is not yet fully supported [1]. Wayland sessions are listed, but SDDM runs on X11.

When I execute `vglserver_config`, it configures the sddm script. `/usr/bin/vglgenkey
`is added to the `/usr/share/sddm/scripts/Xsetup `script. So I don't think Wayland is the issue here. Again thank you very much for your detailed reply.

**Comment by dcommander** [comment]
Once you log out and the glxgears/VirtualGL session is terminated, can you restart `vglrun glxgears` successfully?  If so, then this is a known issue caused by the 3D X server resetting whenever someone logs out, and there isn't anything I can do about it.  But if `vglrun glxgears` doesn't work at all whenever SDDM is sitting at the login prompt, then that's a bug.

**Comment by wddufo** [comment]
> Once you log out and the glxgears/VirtualGL session is terminated, can you restart `vglrun glxgears` successfully?

The answer is no. I can't restart. It produces the same error message.
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  25
  Current serial number in output stream:  26
```
It is very reproducible. If I log in again from the screen connected to the machine, `vglrun glxgears` works fine in a VNC sessions. However, as I mentioned before, if I `su` first, `vglrun glxgears` works well regardless of the local login status. I am really clueless...

**Comment by dcommander** [comment]
OK, in that case, I'll have to install openSUSE and investigate.

**Comment by wddufo** [comment]
> OK, in that case, I'll have to install openSUSE and investigate.

Thanks a lot. Just let me know if you need more information from my setup.

**Comment by wddufo** [comment]
> OK, in that case, I'll have to install openSUSE and investigate.

Somehow `vglrun` works well now on my vnc sessions. I can not reproduce my previous errors. I think you can close this thread. Of course, I will be happy to provide my setup for Tumbleweed if it is necessary. 
Thanks again for your previous suggestions.

**Comment by dcommander** [comment]
Weird, but I'm happy it fixed itself, because I don't really have time right now to test a new O/S.
